### ISSUE TITLE
Schema de la liste des prénoms des nouveaux-nés

### ISSUE THREAD

**Issue by CharlesNepote** [etalab/schema.data.gouv.fr#1]
Ce schéma est celui utilisé par le Socle commun des données locale produit par OpenDataFrance :
https://github.com/CharlesNepote/liste-prenoms-nouveaux-nes

Le .json est dans le repo.

L'intérêt de ce schéma est qu'il comprend peu de champs et qu'il est simple à comprendre (pas besoin de connaissances métiers).

**Comment by abulte** [comment]
Merci @CharlesNepote, c'est intégré : https://github.com/etalab/schema.data.gouv.fr/commit/7a2a36b2cc05444b8fbe3978a8ac617c26e13558
