### ISSUE TITLE
Upgrade schema.json to latest specs

### ISSUE THREAD

**Issue by abulte** [etalab/schema.data.gouv.fr#103]
[Our JSON catalog](https://schema.data.gouv.fr/schemas/schemas.json) does not seem compliant w/ the [latest version of the spec](https://opendataschema.frama.io/catalog/schema-catalog.json), which probably will break w/ the latest version of validata. 

Cf [a reference implementation](https://git.opendatafrance.net/scdl/catalog/raw/master/catalog.json).

**Comment by AntoineAugusti** [comment]
Our JSON catalog is in fact already compliant with the latest version of the specification. I've added a test in CI to enforce this in #104.

PS: seems weird that the JSON schema specification URL does not include a version 🤔

**Comment by abulte** [comment]
sorry, I looked too fast 🙈 

> seems weird that the JSON schema specification URL does not include a version

yep
