### ISSUE TITLE
Métadonnées sur les schémas ne supportent pas les versions

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/schema.data.gouv.fr#109]
Actuellement, schema.data.gouv.fr ne supporte pas le cas où :
- un schéma comporte plusieurs fichiers de schémas (possible pour XSD + JSON Schema)
- ces fichiers changent au cours des différentes versions

En effet, les métadonnées présument que les fichiers sont stables d'une version à l'autre.

## Pratique
On rencontre un problème en production pour le schéma de la commande publique par @ColinMaudry. En version 1.3, il y 2 fichiers de schémas. En 1.4 et 1.5 il n'y a plus qu'un seul fichier. À noter qu'un des fichiers est le même au fil du temps, mais a été renommé (de `marchés.json` à `marches.json`).

Les métadonnées actuelles ne reflètent pas du tout cette situation
https://github.com/etalab/schema.data.gouv.fr/blob/9713524246034e9b182754d707295a1ed83933bb/aggregateur/data/schemas.yml#L9-L17

On se retrouve donc à lister 2 fichiers pour la 1.5, alors qu'il n'y a qu'1. En plus, le lien vers le schéma des marchés n'est pas le bon, le fichier ayant été renommé entre la 1.3 et la 1.5

![image](https://user-images.githubusercontent.com/295709/82460788-9b00ba00-9a87-11ea-9214-1cbe1f4333d6.png)

**Comment by ColinMaudry** [comment]
Pour préciser ce qu'il s'est exactement passé : pour la 1.4, j'ai fusionné les fichiers schémas en un seul. `marchés` et `contrat-concession` ont été intégrés dans paquet, qui a été renommé `marches`.
