### ISSUE TITLE
Remplacer scdl/adresses par BAL générique

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/schema.data.gouv.fr#122]
Voir PR #121 

@jdesboeufs nous avait expliqué sur Slack le risque de confusion qu'il y avait entre ce schéma et les BAL, la BAN. Il me semble qu'il y a des différences entre le validateur BAL et ce schéma, ce qui porte préjudice au développement des BAL.

En conséquence, nous prévoyons de déréfencer ce schéma sur schema.data.gouv.fr et d'ajouter dans les semaines à venir un renvoi vers la BAL/BAN ou de proposer une meilleure intégration.

@jdesboeufs, pourrais-tu ajouter un peu de contexte sur ce ticket pour garder une trace ?

**Comment by abulte** [comment]
TODO: se servir de https://github.com/etalab/schema-generic-template pour référencer le schéma BAL "officiel" décrit ici https://adresse.data.gouv.fr/bases-locales.

**Comment by jdesboeufs** [comment]
Un peu de contexte.

Le format BAL a été créé par l'AITF en 2015, dans le cadre du lancement de la Base Adresse Nationale.
La version 1.1 de la spécification prévoit l'utilisation du séparateur `;` et une liste de champs bien précise.

Au moment de la mise en place du Socle Commune de Données Locales, OpenDataFrance a intégré le format BAL dans la liste, mais en le modifiant. Plusieurs champs obligatoires avaient été ajoutés (retirés depuis), mais surtout les fichiers devaient être conforme TableSchema, et donc utiliser le séparateur `,`.

Ces deux versions ont créé de la confusion, les collectivités participant au programme OpenDataLocale ayant privilégié un temps le format SCDL, celles proches de l'AITF et d'Etalab le format AITF.

Désormais le format reconnu par le projet BAN et par l'écosystème des producteurs est le format BAL de l'AITF.
Néanmoins la plupart des validateurs ne tiennent pas rigueur du séparateur utilisé.

**Comment by jdesboeufs** [comment]
C'est bon du côté https://github.com/etalab/schema-bal je pense.

**Comment by johanricher** [comment]
Bonjour,

Je souhaite rappeler quelques précisions en tant que contributeur au projet [Validata](https://validata.fr/), qui a notamment donné lieu au [schéma BAL du Socle commun des données locales](https://git.opendatafrance.net/scdl/adresses) proposé par OpenDataFrance. Cela ne représente pas la position d’OpenDataFrance (et je viens par ailleurs de les inviter à donner également leur avis sur le sujet).

> les fichiers devaient être conforme TableSchema, et donc utiliser le séparateur `,`

OpenDataFrance avait en effet indiqué dans des documents OpenDataLocale **antérieurs à l’écriture des schémas** que le séparateur de colonnes devait être la virgule. Il s’agissait selon moi d’une recommandation générale à l’intention des producteurs de données. Notez bien qu’en revanche l’utilisation du point-virgule est elle bel et bien imposée par l’AITF. D’un point de vue technique, cette spécification n’a pas lieu d’être et ne se retrouve pas dans les schémas SCDL écrits au format Table Schema. En réalité, Table Schema n’a aucune notion de séparateur, il travaille au niveau au-dessus, sur les données tabulaires et pas leur sérialisation CSV.

Le schéma BAL du SCDL, écrit effectivement en suivant la spécification [Table Schema](https://specs.frictionlessdata.io/table-schema/), n’impose aucunement l’utilisation de la virgule ou du point-virgule. Je vous invite d’ailleurs à essayer de passer un tel fichier dans le [validateur BAL du SCDL](https://go.validata.fr/table-schema?schema_name=scdl.adresses), le rapport n’indiquera pas d’erreur sur ce point.

Dès lors, peut-on clarifier une bonne fois pour toute en quoi le [schéma BAL SCDL](https://git.opendatafrance.net/scdl/adresses/-/raw/master/schema.json) diffère du ["modèle de données visant à alimenter la BAN" AITF](https://cms.geobretagne.fr/sites/default/files/documents/aitf-sig-topo-adresse-fichier-echange-simplifie-v_1.1_0.pdf) ? Cela permettrait de corriger une éventuelle erreur qui n'aurait été aucunement volontaire de la part des auteurs du schéma.

Enfin, au-delà du validateur BAL SCDL (Validata) dont j’entends bien qu’il fait en quelque sorte doublon par rapport à celui d’Adressedatagouv, je pense qu’il y a un intérêt à proposer un réel schéma (et pas simplement un PDF) afin que les producteurs et réutilisateurs de données puissent l’intégrer à une chaîne de traitement existante. Je vois ça comme un complément intéressant aux outils déjà proposés par Adressedatagouv qui visent eux plutôt les utilisateurs finaux grâce à des interfaces intuitives et spécifiquement conçues pour ces données.

**Comment by jdesboeufs** [comment]
Bonjour Johan,

À mon sens c’est le standard scdl/adresses fait doublon avec aitf/bal et qui n’avait pas lieu d’être.
Un schéma structuré peut être intéressant mais ne suffit pas être conforme adresse.data.gouv.fr. C’est pourtant bien cela l’essentiel.
Pour éviter des questions du style « je suis vert ici pourquoi vous refusez mon fichier » nous trouvons plus simple de ne pas proposer d’automatisation au niveau seulement structure pour ce type de données.

Concernant les séparateurs, cela a été problématique au début de Validata. Peut-être plus aujourd’hui.

**Comment by jdesboeufs** [comment]
À noter que nous avons une API et un code de référence : https://github.com/etalab/bal

**Comment by johanricher** [comment]
> À mon sens c’est le standard scdl/adresses fait doublon avec aitf/bal et qui n’avait pas lieu d’être.

L'un est un schéma de données, l'autre un document PDF. Là où tu vois des doublons, je vois des compléments... mais à condition que tout le monde soit d'accord sur la spécification qui doit être source de vérité ! et c'est bien là où je veux en venir.

Car le projet Validata est parti d'un besoin (et pas seulement sur la BAL) qui était de pouvoir disposer d'un schéma technique décorrélé du code, qui puisse évoluer dans le temps avec des versions clairement identifiées, et ce indépendament du validateur. Enfin, la documentation PDF devait être construite directement depuis le schéma et pas l'inverse (source de nombreux problèmes au sein d'OpenDataLocale, avant Validata).

Bref, si tout le monde est d'accord sur la source de vérité, le "standard", pour reprendre le terme que tu utilises, je ne vois pas de problème à ce que différentes implémentations cohabitent.

**Comment by abulte** [comment]
@johanricher Si je serais ravi de proposer un TableSchema conforme pour la BAL, l'argument qui me touche le plus est celui-ci :

> Pour éviter des questions du style « je suis vert ici pourquoi vous refusez mon fichier » nous trouvons plus simple de ne pas proposer d’automatisation au niveau seulement structure pour ce type de données.

Qu'en penses-tu ?

**Comment by johanricher** [comment]
Je pense qu'il faut qu'on prenne un exemple concret pour qu'on soit sûrs de parler de la même chose.

Par exemple, [ce fichier BAL](https://adresse.data.gouv.fr/bases-locales/jeux-de-donnees/5ddff18f6f44411d5f13e271) est jugé "conforme" par le validateur BAL d'Adressedatagouv (ADG). Le même fichier est jugé [non conforme au schéma BAL SCDL par Validata](https://go.validata.fr/table-schema?input=url&schema_name=scdl.adresses&schema_ref=v1.1.4&url=https%3A%2F%2Fstatic.data.gouv.fr%2Fresources%2Fadresses-au-format-bal-saint-esteben%2F20200730-114656%2F20200730-bal-216404764.csv).

Quand on regarde le fichier, on constate qu'il comporte des colonnes inconnues du schéma : `refparc`, `voie_nom_eu` et `complement`. En effet, ces colonnes n'apparaissent nulle part dans la documentation PDF du modèle simplifié d’échange AITF. Le rapport du validateur ADG parle de "champs non reconnus", celui de Validata indique des "erreurs de structure".

En définitive on peut en tirer la conclusion que le validateur ADG juge conforme un fichier qui n'est pas strictement conforme à la documentation PDF.  Si l'insertion de colonnes supplémentaires est autorisé, pourquoi n'est-ce pas indiqué dans la documentation ? Qui a raison ? Quelle est la source de vérité ?

**Comment by abulte** [comment]
@jdesboeufs tu aurais un exemple de fichier "vert" sur Validata et "rouge" sur le validateur BAL ?

@johanricher pour les colonnes supplémentaires, c'est un problème plus large que la BAL je pense. On a souvent des producteurs qui souhaitent rajouter des colonnes vs le schéma et personnellement je ne trouve pas ça choquant. Il faudrait qu'on en parle d'ailleurs mais c'est une autre conversation.

**Comment by johanricher** [comment]
>  On a souvent des producteurs qui souhaitent rajouter des colonnes vs le schéma et personnellement je ne trouve pas ça choquant

Le projet Validata non plus, c'est d'ailleurs pour cela qu'il permet aux utilisateurs de voir le rapport d'erreur sur le contenu, même si la structure est invalide. Il n'y a pas de "punition", ils peuvent voir que tout est bon sauf leurs colonnes supplémentaires, la responsabilité de publier le fichier tel quel leur appartient en dernier lieu.

**Comment by geoffreyaldebert** [comment]
Bonjour à tous,

Pour avancer sur ces débats , la communauté a ces derniers mois actionné les leviers suivants : 
- évolution des catalogues de schémas [pour accepter des schémas non tableschema](https://framagit.org/opendataschema/catalog/-/merge_requests/3)
- évolution de Validata pour accepter des données avec [des colonnes supplémentaires avec la notion de schéma "partiellement valide"](https://git.opendatafrance.net/validata/validata-ui/-/issues/73). En reprenant le même exemple que Johan a soumis ci-dessus, le fichier passe donc désormais les tests sur le schéma SCDL (en mentionnant qu'il y a effectivement des champs supplémentaires par rapport au schéma). Voir [ce rapport de validation](https://validata.etalab.studio/table-schema?input=url&schema_url=https%3A%2F%2Fgit.opendatafrance.net%2Fscdl%2Fadresses%2Fraw%2Fv1.1.4%2Fschema.json&url=https%3A%2F%2Fstatic.data.gouv.fr%2Fresources%2Fadresses-au-format-bal-saint-esteben%2F20200730-114656%2F20200730-bal-216404764.csv).
- ajout de [nouvelles fonctionnalités sur schema.data.gouv.fr](https://github.com/etalab/schema.data.gouv.fr/pull/141) permettant de spécifier des documentations externes (hors documentation tableschema automatiquement générée) ou outils de saisie externe (hors validata) sur la page dédiée au schéma.

Basé sur ces nouveautés, [nous avons ajouté la BAL sur schema.data.gouv](https://schema.data.gouv.fr/etalab/schema-bal/latest.html). Le répertoire github du schéma permettant l'ajout à la plateforme est celui-ci : https://github.com/etalab/schema-bal
