### ISSUE TITLE
Mettre un lieu pour voir les données conformes au schéma sur la page du schéma

### ISSUE THREAD

**Issue by pachevalier** [etalab/schema.data.gouv.fr#124]
Maintenant qu'on peut rechercher les données, on peut ajouter un bouton pour "Voir les données qui respectent le schéma sur Data.gouv.fr en ajoutant un simple lien https://www.data.gouv.fr/fr/datasets/?schema=etalab/schema-irve.

**Comment by abulte** [comment]
Oui !

**Comment by abulte** [comment]
Sur data.gouv.fr (modale schéma) aussi d'ailleurs.

**Comment by AntoineAugusti** [comment]
On en parlait pas plus tard qu'hier, je le fais très bientôt 😉

**Comment by AntoineAugusti** [comment]
See #126

**Comment by AntoineAugusti** [comment]
See https://github.com/etalab/udata-schema-gouvfr/pull/4
