### ISSUE TITLE
Données de stationnement vélo

### ISSUE THREAD

**Issue by JeanneAstier** [etalab/schema.data.gouv.fr#125]
## Description du schéma

transport.data.gouv réalise une investigation pour publier les données de stationnement vélo sur le Point d'Accès National aux données de transport. Dans ce cadre a été construit une première version de schéma de données, selon deux objectifs :

- ce schéma doit pouvoir être adopté par un maximum de producteurs de données - d'où la volonté de ne rendre obligatoires que les champs absolument essentiels.

- ce schéma doit permettre de rassembler des données tournées vers les utilisateurs.

Ce schéma a été réalisé à partir des différents jeux de données publiés par des collectivités ainsi que des données présentes sur OpenStreetMap.

## Liens

Vous pouvez consulter la [proposition de schéma de données](https://docs.google.com/spreadsheets/d/1P-SmgmR3Fos7MMq4jeWi3S4N9KSqy0v6inu8zW4pG-A/edit?usp=sharing) et la commenter directement sur le document.

Pour participer aux discussions de ce schéma, n'hésitez pas à contacter l'équipe en charge du déploiement côté Transport, deploiement@transport.beta.gouv.fr

## Stade d'avancement

Mon schéma est :
- [ ] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [x] **en cours d'élaboration :** ce schéma fait l'objet de discussions auprès de multiples partenaires
- [ ] **en construction :** ce schéma est en cours d'implémentation après son élaboration## Description du schéma

**Comment by Bibi56** [comment]
L'étiquette est "Schéma en construction", le stade d'avancement est "en cours d'élaboration". Une des deux informations (datant du même jour) est sans doute à corriger ;-).

**Comment by gregbodet** [comment]
Bonjour,

Nous venons de prendre connaissance de votre démarche qui nous paraît justifiée et intéressante. Cependant en regardant la proposition de schéma de données, nous nous posons la question du modèle de données d'origine. Comment considérer en un même lieu de stationnement plusieurs types d'équipements possibles. Nous pouvons avoir un stationnement vélo fermé avec accès sécurisé, avec à côté des places en arceaux protégé de la pluie par un toit et à côté des arceaux complémentaires à l'air libre. Comment le schéma de données peut-il répondre à cette question ? Tel qu'il est proposé, le schéma doit intégrer dans ce cas, 3 positionnements correspondant aux 3 types de stationnements ?

Cordialement

**Comment by NicolasBerthelot** [comment]
> Bonjour,
> 
> Nous venons de prendre connaissance de votre démarche qui nous paraît justifiée et intéressante. Cependant en regardant la proposition de schéma de données, nous nous posons la question du modèle de données d'origine. Comment considérer en un même lieu de stationnement plusieurs types d'équipements possibles. Nous pouvons avoir un stationnement vélo fermé avec accès sécurisé, avec à côté des places en arceaux protégé de la pluie par un toit et à côté des arceaux complémentaires à l'air libre. Comment le schéma de données peut-il répondre à cette question ? Tel qu'il est proposé, le schéma doit intégrer dans ce cas, 3 positionnements correspondant aux 3 types de stationnements ?
> 
> Cordialement

Bonjour,
C'est une excellente question. Je pense qu'une solution adaptée pour ces cas-là est effectivement de faire une ligne par type de stationnement quand bien même la position est la même. Ce qui est le plus important reste l'information sur la position de l'équipement et le nombre de places de vélos associées. La multiplication des points au même endroit n'est pas idéale mais pose moins de problèmes que d'indiquer que toutes le places de l'emplacement sont sécurisées si tel n'est pas le cas. 

Qu'en pensez-vous ?

**Comment by gregbodet** [comment]
Bonjour,

Merci pour votre retour.

En fait nous travaillons sur plusieurs sujets avec la même problématique de rattachement d’objets à un lieu. C’est le cas pour nous, des emplacements des lieux de collecte du verre, comprenant des informations aux lieux avec la possibilité d’avoir x conteneurs différents. C’est le cas également pour le standard des réseaux d’eau humides (RAEPA) qui intègre dans son format d’échange la possibilité d’avoir plusieurs points superposés représentant des ouvrages ou des appareillages en un même lieu.

On pourrait donc comme vous le proposez reprendre ce modèle de standard permettant d’avoir plusieurs points en un même lieu. Chaque point représentant un type d’équipements disponibles pour le stationnement de vélo avec ces caractéristiques. Fonctionnellement cela ne change pas grand-chose. Quand on interroge la donnée, on aura x résultats détaillant les emplacements disponibles.

Dans notre collectivité, nous avons adopté ce mode de gestion. Notre base de données gère les informations au lieu avec en relation les classes des équipements, et au format d’échanges, nous régénérons un point par équipement. Pour certaines utilisations, nous générons parfois 1 seul point avec des données agrégées simplifiées avec uniquement par exemple un nb d’équipements disponibles à ce lieu.

Nous pensons donc qu’il faudrait privilégier un format d’échanges permettant la superposition de points correspondant à un type d’équipements  pour vélo avec ces caractéristiques. L’usager pourra ainsi savoir qu’à ce lieu je dispose de 2 arceaux, 1 espace de x stationnements protégés et sécurisés par exemple.

En espérant avoir répondu à vos attentes.

Nous avions laissé également des commentaires dans le fichier de structures de données proposés.

Cordialement


Grégory BODET
Administrateur SIG
Ligne directe : 03 44 86 76 72
gregory.bodet@agglo-compiegne.fr
[geocompiegnois_2020]
https://geo.compiegnois.fr

P Pensez à l'environnement avant d'imprimer ce message



De : NicolasBerthelot [mailto:notifications@github.com]
Envoyé : mardi 13 octobre 2020 18:53
À : etalab/schema.data.gouv.fr <schema.data.gouv.fr@noreply.github.com>
Cc : BODET Gregory <gregory.bodet@agglo-compiegne.fr>; Comment <comment@noreply.github.com>
Objet : Re: [etalab/schema.data.gouv.fr] Données de stationnement vélo (#125)


Bonjour,

Nous venons de prendre connaissance de votre démarche qui nous paraît justifiée et intéressante. Cependant en regardant la proposition de schéma de données, nous nous posons la question du modèle de données d'origine. Comment considérer en un même lieu de stationnement plusieurs types d'équipements possibles. Nous pouvons avoir un stationnement vélo fermé avec accès sécurisé, avec à côté des places en arceaux protégé de la pluie par un toit et à côté des arceaux complémentaires à l'air libre. Comment le schéma de données peut-il répondre à cette question ? Tel qu'il est proposé, le schéma doit intégrer dans ce cas, 3 positionnements correspondant aux 3 types de stationnements ?

Cordialement

Bonjour,
C'est une excellente question. Je pense qu'une solution adaptée pour ces cas-là est effectivement de faire une ligne par type de stationnement quand bien même la position est la même. Ce qui est le plus important reste l'information sur la position de l'équipement et le nombre de places de vélos associées. La multiplication des points au même endroit n'est pas idéale mais pose moins de problèmes que d'indiquer que toutes le places de l'emplacement sont sécurisées si tel n'est pas le cas.

Qu'en pensez-vous ?

**Comment by geoffreyaldebert** [comment]
Le schéma est publié ici : https://schema.data.gouv.fr/etalab/schema-stationnement-cyclable/latest.html
Je close l'issue. N'hésitez pas à la rouvrir si besoin.
