### ISSUE TITLE
Exposer _tous_ les schémas via l'API

### ISSUE THREAD

**Issue by abulte** [etalab/schema.data.gouv.fr#127]
Aujourd'hui nous exposons uniquement les formats au format TableSchema via notre API https://schema.data.gouv.fr/schemas/schemas.json

Pour l'intégration à data.gouv.fr nous avons besoin d'exposer _tous_ les schémas via une API, pas seulement les TableSchema.

L'API actuelle se conforme à un standard https://framagit.org/opendataschema/catalog. Une des pistes est de faire évoluer le standard : https://framagit.org/opendataschema/catalog/-/issues/2.

Une autre piste est de créer une API distincte qui référencerait l'ensemble des schémas.

**Comment by geoffreyaldebert** [comment]
Résolu!
