### ISSUE TITLE
Schéma des hautes rémunérations dans la fonction publique

### ISSUE THREAD

**Issue by geoffreyaldebert** [etalab/schema.data.gouv.fr#130]
## Description du schéma

Spécification du fichier de déclaration des dix rémunérations les plus élevées des agents publiques.

## Liens

Repo Git : https://github.com/etalab/schema-hautes-remunerations

## Stade d'avancement

Mon schéma est :

- [x] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [x] **en cours d'élaboration :** ce schéma fait l'objet de discussions auprès de multiples partenaires
- [x] **en construction :** ce schéma est en cours d'implémentation après son élaboration

**Comment by agarrone** [comment]
## Contributions
Cette issue est dédiée à la réception de contributions de l'ensemble de la communauté afin d'aboutir à un schéma de données reconnu par tous, qui permette d'améliorer la publication et la gestion des données sur les hautes rémunérations dans la fonction publique.

**Comment by hugobarbieux** [comment]
En Angleterre j'ai travaillé avec le gender pay gap. La répartition par genre et par quartile, salaire moyen, salaire médian donnent de particulièrement bons indicateurs à analyser.
Les colonnes du fichier étaient:
DiffMedianHourlyPercent | DiffMeanBonusPercent | DiffMedianBonusPercent | MaleBonusPercent | FemaleBonusPercent | MaleLowerQuartile | FemaleLowerQuartile | MaleLowerMiddleQuartile | FemaleLowerMiddleQuartile | MaleUpperMiddleQuartile | FemaleUpperMiddleQuartile | MaleTopQuartile | FemaleTopQuartile | CompanyLinkToGPGInfo | ResponsiblePerson | EmployerSize | CurrentName

**Comment by alphoenix** [comment]
Hello, pour avoir collecté ces données, une des choses dont on était pas sûr était de la somme des montants, est-ce que c'est du brut, du net, etc. Peut-être est-ce à préciser dans les commentaires, ou peut-être faut-il en faire une modalité spécifique. 

Après, c'est très contraint dans les textes légaux, vu que tout est déjà défini. Est-ce qu'en laissant la possibilité de champs supplémentaires, ça pourrait ouvrir à plus d'informations ? Je ne sais pas. Et surtout quelles informations ?

Le numéro SIREN n'est pas forcément facile à croiser pour des collectivités locales... Peut-être rajouter un champ d'identification géographique ou au moins une classification pour les types d'administrations (Ministère / CR / CD / EPCI / Commune)... 

On peut aussi mettre une contrainte à un max de 120 pour le nombre cumulé de mois.

**Comment by gendy54** [comment]
Plusieurs commentaires:

- Travaillant dans les RH, je confirme ce que dit @alphoenix. Si parler en brut parait une évidence, il faut quand même que l'évidence soit actée.
- Je ne comprends pas le champ "duree_cumulee_mois". Si on a un schéma avec des données annuelles (année civile), pourquoi ce champ? Pour moi c'est forcément sur 12 mois en année pleine
- Du coup, quid des personnes recrutées en cours d'année. On rétablit le salaire comme si elle avait travaillé toute l'année?
- Je ne sais pas si des précisions ont été apportées par des décrets, mais quid des primes diverses et variées. Sont-elles compris dans le total? Idem pour les avantages en nature?
- Quand on parle de "départements ministériels" ca reste au niveau central ou ca concerne aussi les niveaux déconcentrés?

**Comment by alphoenix** [comment]
La durée cumulée en mois permet justement de répondre au troisième point : si une personne est embauchée au cours de l'année, disons sur 5 mois au lieu de 12 mois, les dix plus hauts salaires seront donc sur 9 x 12 mois et 1 x 5 mois, soit 108. Cela permet ensuite de calculer un salaire moyen. 

![image](https://user-images.githubusercontent.com/3621098/104816300-94932f80-581a-11eb-9d66-31fe2ef194b3.png)

Quand au départements ministériels, ce sont des grands sous-ensemble (il y en a douze) et ça ne va pas au-delà. 

Concernant les primes, etc, tout celà est bien détaillé dans la loi : https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000038889209 mais surtout dans les consignes diffusées par la DGAFP et la DGCL. https://www.chu-besancon.fr/fileadmin/user_upload/MEDIATHEQUE/Le_CHRU/30-01-2020_-_Conditions_de_mise_en_oeuvre_de_la_publication_des_dix_plus_hautes_remunerations.pdf

**Comment by geoffreyaldebert** [comment]
Schéma publié via #148 je laisse l'issue ouverte encore quelques temps pour éventuelles réactions de la communauté sur cette première version.
Url de publication du schéma : https://schema.data.gouv.fr/etalab/schema-hautes-remunerations/latest.html
