### ISSUE TITLE
Schéma des lieux de l'inclusion numérique

### ISSUE THREAD

**Issue by raphodn** [etalab/schema.data.gouv.fr#136]
## Description du schéma

[Aidants Connect](https://beta.gouv.fr/startups/aidantsconnect.html) et la [SoNum](https://societenumerique.gouv.fr/) souhaitent cartographier l'ensemble des lieux de l'inclusion numérique en France.

Afin de rendre interopérables l'ensemble des jeux de données disponibles, mais aussi pouvoir ensuite partager la donnée sur des plateformes comme data.gouv, il a été décidé de définir un schéma de donnée.

## Liens

Nos travaux en cours se trouvent [ici](https://github.com/betagouv/Aidants_Connect_Carto/tree/master/schema). Ce dossier contient une première version de notre schema.json.

Un travail a été mené ces derniers mois pour recenser des fournisseurs de données potentiels, échanger avec eux sur leur modèle actuel pour trouver un socle commun, analyser leur jeu de données existants, et les transformer dans un premier temps pour les rendre compatible avec le schema.json. Ce travail est visible dans le dossier connexe [`/data`](https://github.com/betagouv/Aidants_Connect_Carto/tree/master/data). Le wiki du repo donne plus de détails.

Pour contacter l'équipe Aidants Connect Carto en charge de l'élaboration et de l'utilisation de ce schéma : [carto@aidantsconnect.beta.gouv.fr](mailto:carto@aidantsconnect.beta.gouv.fr)

## Stade d'avancement

Mon schéma est :

- [ ] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [x] **en cours d'élaboration :** ce schéma fait l'objet de discussions auprès de multiples partenaires
- [x] **en construction :** ce schéma est en cours d'implémentation après son élaboration

cc @Anna-Livia @BerengereAujard @Camillefwok @Blageir @JulienParis @johanricher

**Comment by geoffreyaldebert** [comment]
Merci pour ce travail, le schéma est publié depuis hier ici : https://schema.data.gouv.fr/etalab/schema-inclusion-numerique/latest.html

**Comment by johanricher** [comment]
Il aurait sans doute été préférable de publier le schéma des lieux d'inclusion numérique dans un dépôt dédié plutôt que dans celui de l'application carto Aidants Connect, et ce pour différentes raisons : 
- le logiciel et le schéma ont vocation à utiliser tous deux les tags Git, ce qui n'est pas possible sur un dépôt commun
- la gouvernance doit être découplée entre le schéma et le logiciel puisqu'ils impliquent des personnes et concernent des utilisateurs différents
- en résumé : ce sont des projets distincts

J'avais fait cette remarque au moment de l'écriture du guide de création des schémas, on en trouve une trace [ici](https://guides.etalab.gouv.fr/producteurs-schemas/phase-construction/#points-de-sortie) : "Avoir publié votre travail en ligne, dans un répetoire Git dédié". Il serait peut-être utile de rendre cela plus apparent en ajoutant des précisions quant aux raisons qui justifient cela. Si vous êtes d'accord avec cette idée, je proposerais une PR @geoffreyaldebert @abulte.

**Comment by AF02** [comment]
Bonjour 
Le schéma sur l'inclusion numérique n'est plus disponible sur data Gouv
