### ISSUE TITLE
Référencement d'un schéma sur les menus de la restauration collective

### ISSUE THREAD

**Issue by akakeronos** [etalab/schema.data.gouv.fr#149]
## Description du schéma
Ce schéma permet de décrire la composition des menus proposés par les collectivités locales ou les syndicats mixtes de restauration. Il est porté par l'association Open Data France en concertation avec les collectivités pilotes et les éditeurs de logiciels.
Il a comme finalité d'harmoniser les publications de données ouvertes concernant la composition des menus de la restauration collective

## Liens
https://git.opendatafrance.net/scdl/menus-collectifs/

## Stade d'avancement

Mon schéma est :

- [ ] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [X] **en cours d'élaboration :** ce schéma fait l'objet de discussions auprès de multiples partenaires
- [ ] **en construction :** ce schéma est en cours d'implémentation après son élaboration

Actuellement le schéma est au stade pre-release, dernier appel à commentaires

**Comment by geoffreyaldebert** [comment]
Bonjour @akakeronos,

Merci et bravo pour ce travail et ce schéma qui j'en suis sûr sera très utile ! Je vois qu'un certain nombre d'acteurs ont participé à l'élaboration de ce schéma, c'est super.

Je vous donne mes remarques ci-dessous : 
- Ajouter le format pour le champs date `menu_date` (exemple [ici](https://github.com/etalab/schema-lieux-covoiturage/blob/a89ace20ca76d08be825df2e2fd217496cb0abe3/schema.json#L153)) 
- Pour la propriété `menu_prix_plat`, pourquoi ne pas indiquer dans la description que le prix doit être en euros et de passer le champ en `number`

N'hésitez pas à reprendre contact sur ce fil ou via schema [at] data.gouv.fr lorsque vous serez prêt à publier ce schéma.

**Comment by akakeronos** [comment]
Bonjour @geoffreyaldebert 
Merci pour votre réponse. Je vais procéder aux modifications suggérées. Concernant le nommage des champs, avez-vous des préconisations ?

**Comment by akakeronos** [comment]
Bonjour @geoffreyaldebert
Le schéma des menus de la restauration collective est maintenant publié
https://git.opendatafrance.net/scdl/menus-collectifs
https://scdl.opendatafrance.net/docs/schemas/menus-collectifs.html

Pourriez-vous le rajouter à votre catalogue des schémas publiés ?

Merci d'avance

**Comment by geoffreyaldebert** [comment]
Bonjour @akakeronos ,

Encore bravo pour ce schéma. Celui-ci est désormais publié sur schema.data.gouv : https://schema.data.gouv.fr/scdl/menus-collectifs/latest.html.

Je ferme l'issue mais n'hésitez pas à nous faire un retour si besoin et la rouvrir.

**Comment by akakeronos** [comment]
Bonjour @geoffreyaldebert merci pour cette publication !
Un second schéma arrive pour le détail des plats des menus. J'ouvre un nouveau ticket.
J'en profite pour vous demander si vous pouvez modifier le statut du schéma sur les budgets qui n'est plus en cours de travail mais bien au statut publié ? Merci d'avance

**Comment by geoffreyaldebert** [comment]
Bonjour @akakeronos,

Super pour ce nouveau schéma et ok, j'aibien modifié le statut du schéma des budgets.
Bonne journée !
