### ISSUE TITLE
Schéma Arrêtés Permanents de Circulation

### ISSUE THREAD

**Issue by mrajerisonCerema** [etalab/schema.data.gouv.fr#157]
## Description du schéma
Ce schéma sur les arrêtés permanents de circulation concerne la règlementation de la circulation en ville : types de véhicules, usages, longueur du véhicule, plages horaires, etc...

Voici un exemple totalement fictif : 
>"D'après l'arrêté AP-13090-43, sur la commune d'Aix-en-Provence, les véhicules de plus de 3.5 T ne sont pas autorisés à circuler sur l'avenue Philippe Solari le week-end entre 18h et 24h, à l'exception des véhicules de secours et d'urgence."

Ce schéma a été produit par le Cerema, en partenariat avec la région Sud, OpenDataFrance et la Fabrique de la Logistique.

## Liens
[Dépôt github](https://github.com/CEREMA/schema-arrete-permanent-circulation)
[Documentation](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md)
[Diagramme des champs](https://raw.githubusercontent.com/CEREMA/schema-arrete-circulation/master/arrete-permanent-circulation.png)
[schema.json](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema.json)
[Page relative au schéma sur OpenDataFrance](https://opendatafrance.gitbook.io/fablog/territoires/chantiers/partage-des-donnees/standardisation/arretes-de-circulation)

## Stade d'avancement
Le schéma a été produit par le Cerema à la suite d'une expérimentation locale, conduite avec la Région Sud, autour d'[un outil de dématérialisation des arrêtés de circulation, de livraison et de stationnement](https://gitlab.cerema.fr/mathieu.rajerison/arretes-marchandises-user/-/wikis/home).

[Le schéma été hébergé par OpenDataFrance et présenté en FabLog (Fabrique de la Logistique)](https://opendatafrance.gitbook.io/fablog/territoires/chantiers/partage-des-donnees/standardisation/arretes-de-circulation).

## 📣 Appel à Contributions
L'objet de cette diffusion est de recueillir un avis : 

- sur les champs, leur nommage, leur nature
- les **référentiels de valeurs** utilisées pour des champs (comme les usages : livraison, secours, etc...)

👉[Vous pouvez passer par ce Google Forms pour contribuer au schéma
](https://forms.gle/k2kmGhTGri7MKUuC9)

### Types d'usages
En particulier, il est recherché une exhaustivité la plus complète pour les [types d'usages associés aux véhicules (champ `VEH_USAGE`)](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#type-d'usage---propri%C3%A9t%C3%A9-veh_usage). 

Pour le moment, les valeurs sont : 

> Autocars
> Convois funéraires
> Bennes à ordures ménagères
> Citernes
> Commerçant nomade
> Commerçant sédentaire
> Desserte locale : déménageur
> Livraison
> Poids lourds d'urgence
> Professions médicales
> Riverains
> Services publics
> Taxis
> Transport de carburant
> Transport de denrées animales ou végétales
> Transport de fonds
> Transport de gaz
> Transport de matières dangereuses
> Transports en commun
> Véhicules d'approvisionnement des marchés
> Véhicules effectuant du transport exceptionnel au sens de l'article R.433-1 du code de la route et munis d'une autorisation préfectorale
> Véhicules de police
> Véhicules de secours
> Véhicules de transport de matériaux
> Véhicules de travaux
> Véhicules municipaux
> Véhicules munis d'une autorisation
> Véhicules porte-voitures
> Voitures de Transport avec Chauffeur

De même, il y a d'autres référentiels de valeur utilisés, pour lesquels des retours seraient utiles sur : 

- [le type de zone](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#propri%C3%A9t%C3%A9-zone_type)
- [le type de véhicules](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#propri%C3%A9t%C3%A9-veh_type)
- [le type de motorisation](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#type-de-motorisation---propri%C3%A9t%C3%A9-veh_motor)
- [les étiquettes CQA](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#vignettes-crit'air---propri%C3%A9t%C3%A9-veh_cqa)

## Conventions de nommage
Dans ce schéma, les champs sont écrits en majuscules. Le préfixe indique la famille du champ. Ces familles sont visualisables sur [le diagramme des champs](https://raw.githubusercontent.com/CEREMA/schema-arrete-circulation/master/arrete-permanent-circulation.png). 

![](https://raw.githubusercontent.com/CEREMA/schema-arrete-circulation/master/arrete-permanent-circulation.png)

## Autorisation ou Interdiction
Dans certains cas, un arrêté peut autoriser la circulation de véhicules d'un certain type dans certaines plages horaires. Dans d'autres cas, il peut interdire. Afin de résoudre cette problématique autorisation/interdiction, le schéma propose un champ [`REGL_MODALITE`](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#propri%C3%A9t%C3%A9-regl_modalite) prenant comme valeurs `Autorise` ou `Interdit`

## Jours et horaires
Les jours et horaires sont formalisés dans un champ [`PERIODE_JH`](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#jours-et-heures-de-circulation---propri%C3%A9t%C3%A9-periode_jh) au format [Opening Hours](https://wiki.openstreetmap.org/wiki/Key:opening_hours) d'OpenStreetMap.

## Géométrie
Dans ce schéma, les champs [GEOM_JSON](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#g%C3%A9om%C3%A9trie-au-format-geojson---propri%C3%A9t%C3%A9-geom_json) et [GEOM_WKT](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#g%C3%A9om%C3%A9trie-au-format-wkt---propri%C3%A9t%C3%A9-geom_wkt) permettent, au choix, d'intégrer la géométrie de la voie, ou de la portion de voie réglementée. Le support du WKT (Well Known Text) a été autorisé car ce dernier est plus familier dans les services SIG que le JSON.

### Début et fin
Des champs [SECTION_DEBUT_POINT](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#d%C3%A9but-de-la-section---propri%C3%A9t%C3%A9-section_debut_point) et [SECTION_FIN_POINT](https://github.com/CEREMA/schema-arrete-permanent-circulation/blob/master/schema-page.md#fin-de-la-section---propri%C3%A9t%C3%A9-section_fin_point) permettent de signaler les début et fin de chaque section règlementée sur la voie.

----

Mon schéma est :

- [ ] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [ ] **en cours d'élaboration :** ce schéma fait l'objet de discussions auprès de multiples partenaires
- [x] **en construction :** ce schéma est en cours d'implémentation après son élaboration

**Comment by geoffreyaldebert** [comment]
Bonjour,

Merci pour ce message et cette proposition très prometteuse de schéma. Je regarde dans les prochains jours le détail de celui-ci et revient vers vous dans ce fil.

Pour les visiteurs de cet issue, n'hésitez pas à poster ici vos commentaires.

Bonne journée,

**Comment by mrajerisonCerema** [comment]
[📣 N'hésitez pas à contribuer : vous pouvez contribuer au schéma via ce Google Forms, visant à consolider les valeurs présentes dans certaines listes (types de véhicules, usages des véhicules, ....)](https://docs.google.com/forms/d/e/1FAIpQLSeMOTpg36KcATKlWHtlWJldJ27a7rRdkgF2-LuE8F60hHPDoQ/viewform)

**Comment by geoffreyaldebert** [comment]
Le schéma est publié : https://schema.data.gouv.fr/CEREMA/schema-arrete-circulation-marchandises/latest.html

N'hésitez pas à rouvrir l'issue en cas de question.

**Comment by johanricher** [comment]
Il y a quelques coquilles dans le schéma, notamment les `path` des fichiers exemples qui pointent vers les blobs Github au lieu des fichiers bruts. Il manque aussi les tags git dans les URL et le champ `lastModified` n'a pas été mis à jour.

**Comment by mrajerisonCerema** [comment]
Merci beaucoup @johanricher

Je viens de corriger les `paths` ainsi que `lastModified`
https://github.com/CEREMA/schema-arrete-circulation-marchandises/blob/master/schema.json

Par contre, peux-tu nous dire comment indiquer les tags git dans les URLs ?

**Comment by johanricher** [comment]
Le tag git remplace la branche dans l'URL, exemple : https://github.com/etalab/tableschema-template/blob/master/schema.json#L25

Pour trouver facilement cette URL pour chaque fichier il suffit de basculer sur le tag grâce au menu en haut à gauche : 

![image](https://user-images.githubusercontent.com/10212787/133098039-87ddc8bb-b969-4475-bf95-730f9593ebfc.png)

Ensuite il y a un bouton "Raw" sur la page Github de chaque fichier, il suffit alors de copier le lien pour récupérer l'URL du fichier brut sur le bon tag.

**Comment by mrajerisonCerema** [comment]
ah oui, ok. En fait, je pensais qu'il fallait inclure un tag du type keyword, ou quelque chose comme ça, au sein de resources

Je le fais de suite.

Encore merci :)

**Comment by johanricher** [comment]
Super ! :+1: 
Dernière chose, il faudrait aussi que le `path` du schéma pointe vers la bonne version du schéma sur git (en l'occurrence [celle avec le tag `v0.6.3`](https://github.com/CEREMA/schema-arrete-circulation-marchandises/blob/v0.6.3/schema.json)) et pas la version sur master (qui peut être une prochaine version sur laquelle il y a un travail en cours par exemple). En fait c'est la même chose pour tous les fichiers référencés dans le schéma qui sont stockés dans le même dépôt Git. L'idée derrière ça c'est d'utiliser le versionnement et les tags Git pour faire une photographie à l'instant-t du schéma et de toutes les ressources (donc pointer vers un fichier sur la branche master n'est pas satisfaisant car il va changer dans le temps).

**Comment by mrajerisonCerema** [comment]
C'est fait : https://github.com/CEREMA/schema-arrete-circulation-marchandises/blob/v0.6.3/schema.json
Vraiment sympa de nous aider à rendre ça d'équerre
Encore merci !

**Comment by johanricher** [comment]
Avec plaisir, bravo pour ton travail et celui des autres contributeurs. :clap:
