### ISSUE TITLE
harmonisation listes des schémas

### ISSUE THREAD

**Issue by akakeronos** [etalab/schema.data.gouv.fr#165]
Je vous contacte par ce biais au nom d'OpenDataFrance. Si vous préférez on peut poursuivre par email.

Je souhaiterai discuter avec vous des modalités de référencement des schémas de données publiés par notre association ainsi que de l'harmonisation de leur présentation.

**Comment by geoffreyaldebert** [comment]
Bonjour @akakeronos ,

Je viens de vous écrire un mail (en espérant avoir le bon) pour vous proposer un rendez-vous. N'hésitez pas à me signaler si vous ne l'avez pas reçu ou bien à nous écrire à schema@data.gouv.fr 

Bonne journée,

Geoffrey
