### ISSUE TITLE
Support des schémas XML et JSON

### ISSUE THREAD

**Issue by ColinMaudry** [etalab/schema.data.gouv.fr#17]
Pour l'instant, il semble que ce projet fasse la part belle aux schémas Table Schema, pour la validation de fichiers CSV.

Des développements sont-ils nécessaires pour intégrer ces schémas ? Je pense évidemment aux DECP, qui intègrent 2 schémas : un schéma XML et un schéma JSON.

**Comment by abulte** [comment]
La mécanique de base (publication) devrait fonctionner, on y a pensé ! Il faut juste, je pense, se mettre d’accord pour la valeur à donner à `type` dans ton cas.

**Comment by flacombe** [comment]
Bonsoir 

Il y a egalement le format Avro qui permet de formaliser des structures de plusieurs natures. C'est d'abord un serialiseur qui s'accompagne d'une solide approche schéma

Je m'en sert actuellement pour décrire des fichiers csv et json (donc geojson par extension)

Voir ici : http://avro.apache.org/docs/1.8.2/spec.html

L'intérêt est que ce n'est pas couplé à un format, comme le xsd peut l'etre avec le xml

**Comment by AntoineAugusti** [comment]
Il n'y a pas d'a priori sur les formats de schémas. Pour intégrer un autre type, il faut écrire une classe de validation, capable de valider qu'un dépôt dans une version donnée est validé et d'extraire les fichiers. Voir

**Comment by flacombe** [comment]
Ok je vais voir ce que je peux faire sur la question
Merci @AntoineAugusti

**Comment by AntoineAugusti** [comment]
@ColinMaudry @flacombe N'hésitez pas à me contacter directement si vous avez besoin d'aide. Si vous avez des spécifications pour un format précis, je peux envisager d'écrire le validateur correspondant.

Il faut savoir comment valider que le schéma est valide, quels sont les fichiers à extraire etc.

**Comment by abulte** [comment]
NB : dans une première version, on peut se passer de vérifier que le schéma est valide, juste vérifier qu'il est présent. Ça peut être très simple ;-)

**Comment by AntoineAugusti** [comment]
Hello,

Les schémas XSD sont désormais supportés grâce à la PR https://github.com/etalab/schema.data.gouv.fr/pull/26. Elle intégre la possibilité d'avoir plusieurs schémas XSD dans un même dépôt.

@ColinMaudry je te ferai une PR pour ajouter un fichier `schemas.yml` à la racine [comme requis](https://schema.data.gouv.fr/documentation/validation-schemas#validations-sp%C3%A9cifiques-au-format-xml-schema-definition-xsd).

**Comment by AntoineAugusti** [comment]
Et le support des schémas en JSON schema est effectif depuis #28. Je clos donc cette issue.
