### ISSUE TITLE
Schéma des points d'eau incendie

### ISSUE THREAD

**Issue by tportier** [etalab/schema.data.gouv.fr#181]
## Description du schéma
Aujourd’hui les points d’eau incendie (borne incendie, poteau incendie et autres points d’eau) sont recensés par les SDIS, les collectivités territoriales et/ou les délégataires de service public.
La consolidation de ces données est effectuée à un échelon départemental. Ces bases constituent un enjeu majeur pour la gestion des risques incendie et doivent pouvoir être partagées facilement entre organisations.

Ce modèle de données à été créé dans le cadre du groupe de travail Open Data de l'AFIGEO

## Liens
* [Référentiel national DECI](https://www.interieur.gouv.fr/content/download/91185/709898/file/r%C3%A9f%20nat%20DECI%20du%2015%20d%C3%A9c%202015.pdf)
* [Modèle de données AFIGEO](https://www.afigeo.asso.fr/wp-content/uploads/2020/12/10/modele-minimal-donnees-pei.pdf)
* [Liste des implémentations](https://docs.google.com/spreadsheets/d/1UBlX52Of20q4HnAFTyxrfX75vZrUtXDxwXP6j6_kUp4/edit#gid=0)
* [Dépôt GIT](https://gitlab.com/datakode/schema-pei)

## Stade d'avancement
Mon schéma est :
- [ ] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [ ] **en cours d'élaboration :** ce schéma fait l'objet de discussions auprès de multiples partenaires
- [x] **en construction :** ce schéma est en cours d'implémentation après son élaboration

**Comment by geoffreyaldebert** [comment]
Bonjour @tportier et merci pour votre issue.

Je vois que vos réflexions et le schéma est déjà bien avancé, souhaitez-vous que nous fassions une réunion sur le sujet dans les prochaines semaines pour envisager un planning d'intégration du schéma sur schema.data.gouv ?

Je vous laisse nous contacter à notre adresse générique schema [at] data.gouv.fr

Bonne journée,

Geoffrey Aldebert
Etalab
