### ISSUE TITLE
Anciens liens documentation des schémas cassés

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/schema.data.gouv.fr#195]
D'anciens liens apparaissent comme cassés avec la nouvelle version. #192 

- Ancien : https://schema.data.gouv.fr/etalab/schema-irve/2.0.0.html
- Nouveau https://schema.data.gouv.fr/etalab/schema-irve/2.0.0/.

Faire des redirections serait envisageable ?

**Comment by AntoineAugusti** [comment]
Utiliser https://www.npmjs.com/package/vuepress-plugin-redirect-frontmatter ou autre ?

**Comment by geoffreyaldebert** [comment]
Fix by #196 
Je n'ai pas implémenté la redirection frontmatter qui fonctionnait mal, donc j'ai préféré copier les fichiers pour qu'ils puissent répondre aux adresses posant problème. Cela ne devrait plus poser de problème.
