### ISSUE TITLE
Mieux spécifier IRVE

### ISSUE THREAD

**Issue by CharlesNepote** [etalab/schema.data.gouv.fr#2]
Chouette le schema des données IRVE ! Quelques remarques, j'espère constructives, pour l'améliorer :

- documenter dans le schéma un peu d'infos contextuelles : auteur, etc.
- mieux documenter chaque champ
- donner des exemples de valeurs pour chaque champ
- introduire des regexp de validation : exemple pour le code INSEE : "pattern": "^([013-9]\\d|2[AB1-9])\\d{3}$"

Vous pouvez jeter un oeil à ce que j'ai produit comme exemple pour les prénoms des nouveaux-nés : 
https://github.com/CharlesNepote/liste-prenoms-nouveaux-nes/blob/v1.1.1/prenom-schema.json

**Comment by abulte** [comment]
Bonjour @CharlesNepote, merci pour ces retours ! L'idée était effectivement de démarrer avec quelque chose de simple et de voir ce que la communauté pouvait proposer comme améliorations. Je prends un peu de temps dès que possible pour faire une passe selon tes suggestions.

**Comment by abulte** [comment]
@CharlesNepote j'ai intégré quelques améliorations dans #3. Je suis preneur de PRs sur le reste, par exemple pour des regexe sur les ids de station et de borne ! Pour l'instant j'ai choisi de ne pas me "trimballer" une gestion de version, même si ça deviendra vite utile quand|si le schéma est utilisé.

**Comment by pierredittgen** [comment]
Bonjour,

Merci pour ce premier schéma !
[Validata](https://go.validata.fr) pourrait être le premier utilisateur du schéma IRVE.

À ce titre, nous préconisons de créer un dépôt par schéma pour pouvoir synchroniser les versions du schéma (propriété `version` de schema.json) avec un tag de version du dépôt comme par exemple pour le schéma des [marchés publics](https://git.opendatafrance.net/scdl/marches-publics)

Serait-ce envisageable d'extraire ce schéma dans un dépôt git propre ?

**Comment by abulte** [comment]
Bonjour @pierredittgen,

Super nouvelle !

Pour l'instant nous sommes plutôt parti sur l'idée de tout centraliser sur un seul dépôt -- notamment afin d'en faciliter la maintenance. Toutefois nous sommes ouverts à la discussion.

Vous pouvez peut-être envisager de pointer vers le `schema.json` directement, en utilisant un numéro de commit pour gérer la version ?

**Comment by abulte** [comment]
@pierredittgen j'ai créé une autre issue pour parler de ce point : https://github.com/etalab/schema.data.gouv.fr/issues/4

**Comment by AntoineAugusti** [comment]
Pour les futures suggestions sur ce schéma, il faudra aller voir du côté de https://github.com/etalab/schema-irve
