### ISSUE TITLE
Elaboration de schémas de comptage des mobilités 

### ISSUE THREAD

**Issue by Miryad3108** [etalab/schema.data.gouv.fr#208]
## Description du schéma

Dans le cadre des travaux de l’équipe du Point d’accès national et de la mise en œuvre de l’ouverture des données pour améliorer l’information dont disposent les voyageurs, l’équipe de transport.data.gouv.fr, en collaboration avec l'association Vélo & Territoires et Eco-compteur et un groupe de travail composé de : 
- collectivités : villes d'Angers, de Brest, de Montpellier, d'Alençon et de Paris, le syndicat intercommunautaire Ouest Cornouaille Aménagement, les communautés de communes Touraine et d'Annemasse , la communauté d'agglomération du Grand Chambéry, la communauté urbaine Grand Poitiers, les métropoles de Nantes, Grand Lyon, Grenoble, Bordeaux et de Rouen, les départements du Finistère et d'Ille-et-Vilaine, les régions Bretagne, Île-de-France, Hauts-de-France et  Centre - Val de Loire
- fournisseurs de données de comptage : Eco-Compteur, Metrocount, Alyce, Sterela, TagMaster, Wintics
- association : Association droit au vélo

propose une solution simple et structurée pour l’ouverture des données de comptage des mobilités : le schéma national de comptage des mobilités. Il s’adresse à toute collectivité qui souhaite se lancer dans l’ouverture de jeux de données décrivant la fréquentation de leurs infrastructures.

Trois ateliers ouverts (le 23/04/2021) le 17/06/2021, et le 28/09/2021) ont permis sa production. Il a notamment été établi après des entretiens avec différents fournisseurs de solutions de comptage (Eco-Compteur, Metrocount, Alyce, Sterela, TagMaster, Wintics) afin de nous assurer que les champs proposés répondaient bien à leurs besoins et compétences. Ce schéma permet de recenser les sites de comptages et de comptabiliser la fréquentation d'infrastructures.

L’ouverture des données sur le comptage des mobilités ne répond à aucune obligation réglementaire et n'est pas encadrée par le Règlement Européen (UE 2017 1926) ni par la Loi d'Orientation des Mobilités.

Les collectivités harmonisent et publient donc ces données librement.

## Liens

Documentation externe : https://doc.transport.data.gouv.fr/producteurs/comptage-des-mobilites

## Stade d'avancement

Mon schéma est :

- [ ] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [x] **en construction :** ce schéma est en cours d'implémentation après son élaboration

**Comment by geoffreyaldebert** [comment]
Bonjour @Miryad3108, @thbar

Merci pour cette proposition de schémas.

Pour la communauté, les trois schémas proposés sont hébergés ici : 
- Site : https://github.com/etalab/comptage-mobilites-site
- Channel : https://github.com/etalab/comptage-mobilites-channel
- Measure : https://github.com/etalab/comptage-mobilites-measure

Nous avons plusieurs remarques avant de valider ces schémas et les référencer sur schema.data.gouv.fr : 
- Renommer les repos github en "schema-XXX" (ex : "schema-comptage-mobilites-site") pour bien comprendre qu'il s'agit d'un repo concernant un schéma (c'est principalement utile pour la gestion des repo sur l'organisation Etalab). Attention, cela va impacter plusieurs champs dans chacun de vos fichiers schema.json (notamment la homepage et les fichiers exemples)
- Modifier les url des fichiers exemples explicités dans les fichiers schema.json de ces 3 repo. En effet, ceux-ci font référence au fichiers exemples de la branche master (qui peut être amenée à évoluer) et non pas de la release auquel ils font référence.
  - par exemple : `https://github.com/etalab/comptage-mobilites-channel/blob/master/exemple-valide.csv` devrait être `https://raw.githubusercontent.com/etalab/comptage-mobilites-channel/v0.1.0/exemple-valide.csv` 

Pour faire ces modifications, il faudra peut-être monter de release (ou supprimer et remplacer la v0.1.0 actuelle, comme vous préférez).

Enfin, ces 3 schémas sont en effet un cas particulier car un même objet (le comptage des mobilités) a besoin de trois fichiers plat (csv). C'est un cas encore à ce jour non rencontré sur schema.data.gouv.fr mais que nous avons déjà identifié, notamment avec @johanricher 

Lors de la publication, ceux-ci apparaitront sur le site comme 3 schémas distincts, faute de fonctionnalité actuel sur schema.data.gouv.fr permettant de "regrouper" plusieurs schémas sur un même objet. Est-ce que cela vous convient ?

De plus, si nous développons dans les prochains mois une fonctionnalité permettant de regrouper plusieurs schémas sur une même carte sur schema.data.gouv.fr, serait-il envisageable pour vous de regrouper ces 3 repos en un seul (avec plusieurs fichiers json dans le même repo) ? 

Merci et à très vite,

Geoffrey

**Comment by thbar** [comment]
Merci @geoffreyaldebert pour ces retours et les explications associées.

Nous avons tout renommé:
- les repositories
- le champ `name` dans `schema.json`
- les liens de ressources
- les readme

> il faudra peut-être monter de release (ou supprimer et remplacer la v0.1.0 actuelle, comme vous préférez).

J'ai recréé les tags et les releases (toujours `v0.1.0`).  

> Lors de la publication, ceux-ci apparaitront sur le site comme 3 schémas distincts, faute de fonctionnalité actuel sur schema.data.gouv.fr permettant de "regrouper" plusieurs schémas sur un même objet. Est-ce que cela vous convient ?

Oui cela nous convient pour commencer ; merci de considérer cette feature !

> si nous développons dans les prochains mois une fonctionnalité permettant de regrouper plusieurs schémas sur une même carte sur schema.data.gouv.fr, serait-il envisageable pour vous de regrouper ces 3 repos en un seul (avec plusieurs fichiers json dans le même repo) ?

Non seulement c'est envisageable mais ça serait même un gros + pour nous. On peut mutualiser plus facilement le readme, les GitHub actions qui vérifient les choses, les mises à jour de Python associées, et de façon générale ça sera plus clair pour les contributeurs et utilisateurs.

Donc complètement partant, et d'ailleurs heureux de participer à votre beta si vous voulez utiliser notre schéma comme test là dessus.

Voilà - de notre côté je pense n'avoir rien oublié, mais n'hésite pas, à votre disposition pour aider à publier.

**Comment by geoffreyaldebert** [comment]
Les schémas sont en ligne. Je constate un problème au niveau du README, les liens vers les fichiers locaux, sont relatifs. Est-ce possible de mettre des liens complets car schema.data.gouv.fr ne les interprète pas bien.

**Comment by thbar** [comment]
@geoffreyaldebert je vais aller regarder, merci !

**Comment by johanricher** [comment]
Je note qu'OpenDataFrance a suivi la même approche avec le schéma [menus restauration collective](https://scdl.opendatafrance.net/docs/schemas/menus-collectifs.html) et [plats des menus de la restauration collective](https://scdl.opendatafrance.net/docs/schemas/plats-menus-collectifs.html).

Pour ma part je suis assez circonspect sur la maintenabilité de jeux de données s'appuyant sur des schémas multiples. On est plus dans une logique de système d'information, et de bases de données dites "métier", que dans les principes de l'open data où chaque fichier (+ métadonnées) publié devrait pouvoir être compris par un humain en dehors sans nécessité de contexte ou de fichier supplémentaires.

Je ne serais pas surpris qu'à terme soit produite une version simplifiée en seul fichier plutôt que trois, ce qui facilitera la réutilisation de ces données.

Je vois cependant ces schémas comme une expérimentation à mener, et que je suis suivrai à ce titre avec grand intérêt !

**Comment by thbar** [comment]
@johanricher merci pour le retour ! Sur le cas présent, c'est un schéma très collé aux industriels et utilisateurs, mis au point en ateliers (ce fût d'ailleurs long). Je pense que ça s'explique par le fait qu'effectivement, le producteur est dans ce cas presque toujours un outil du marché en général (ils vont modifier leurs systèmes). 

On n'hésitera pas à partager les avantages et inconvénients rencontrés :-)

**Comment by thbar** [comment]
@geoffreyaldebert j'ai corrigé le point suivant:

> Les schémas sont en ligne. Je constate un problème au niveau des README, les liens vers les fichiers locaux, sont 
> relatifs. Est-ce possible de mettre des liens complets car schema.data.gouv.fr ne les interprète pas bien.

Et j'ai créé #212 avec mes retours.

Comment puis-je "rafraichir" le schéma ?

**Comment by geoffreyaldebert** [comment]
@thbar merci pour la prise en compte des URLs complets sur vos README.

A priori tout est bon, le rafraichissement de schema.data.gouv.fr s'effectue toutes les nuits. Je ne constate plus le problème donc je ferme l'issue, n'hésitez pas à la rouvrir si besoin. 

Félicitations pour ces trois nouveaux schémas.
