### ISSUE TITLE
Schéma des prénoms

### ISSUE THREAD

**Issue by akakeronos** [etalab/schema.data.gouv.fr#209]
## Description du schéma
Ce schéma permet aux communes de publier la liste des prénoms des nouveaux-nés référencés dans l’État civil de leur commune. Il a été élaboré par Charles Nepote (à l'époque membre de la Fing) avec la collaboration de plusieurs membres de la communauté open data. Il permet d'établir des statistiques relatives à l'occurrence des prénoms sur le territoire français

## Liens
Le cadre réglementaire s'appuie sur différents texte liés à la gestion des actes d’État civil : 

* Circulaire du 28 octobre 2011 relative aux règles particulières à divers actes de l'état civil relatifs à la naissance et à la filiation — NOR : JUSC1119808C (lien)
* Circulaire du 23 juillet 2014 relative à l’état civil — NOR : JUSC1412888C (lien)

Il est actuellement publié sur la forge d'opendatafrance à l'url https://git.opendatafrance.net/scdl/prenoms.git

## Stade d'avancement

Mon schéma est :

- [ ] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [x ] **en construction :** ce schéma est en cours d'implémentation après son élaboration

**Comment by geoffreyaldebert** [comment]
Merci @akakeronos,

Très bonne nouvelle si Opendatafrance via le scdl reprend ce schéma qui n'était plus maintenu et en erreur depuis de nombreux mois.

Je mets à jour schema.data.gouv.fr avec celui-ci.

Geoffrey

**Comment by geoffreyaldebert** [comment]
le schéma est publié : https://schema.data.gouv.fr/scdl/prenoms/
