### ISSUE TITLE
Supprimer clé obligatoire contact pour TableSchema

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/schema.data.gouv.fr#21]
La clé contact est redondante avec la clé author pour TableSchema. Ceci est bloquant pour les schémas du SCDL par exemple.

Supprimer le caractère obligatoire de cette clé.

Cc @johanricher

**Comment by johanricher** [comment]
Comme discuté précédemment, nous essayons pour l'instant de faire évoluer la spec Table Schema pour qu'elle intègre une propriété `contributors` qui aurait elle-même des propriétés `email` et `role` ([à l'instar de la spec Data Package](https://frictionlessdata.io/specs/data-package/#contributors)).

En attendant que ce soit fixé ([PR à suivre](https://github.com/frictionlessdata/specs/pull/630)), je propose effectivement de relâcher les contraintes (i.e. chacun fait comme il veut).
