### ISSUE TITLE
Ajout de badges / labels

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/schema.data.gouv.fr#22]
Introduire des badges pour mettre en évidence les schémas issus d'une voie réglementaire ou ceux qui proviennent du SCDL (poke @johanricher).

**Comment by johanricher** [comment]
Une possibilité pourrait être de s'appuyer sur une propriété [`keywords`](https://frictionlessdata.io/specs/data-package/#keywords), que nous souhaitons voir implémentée dans la spec Table Schema, et qui permettrait de tagguer les schémas avec des mot-clés : "SCDL", "réglementaire", etc.

**Comment by AntoineAugusti** [comment]
Ce sera Etalab qui donnera ces labels donc on ne peut pas se reposer sur des propriétés déclarées dans les schémas. De plus, ce n'est pas forcément acceptable pour tous les types de schémas.
