### ISSUE TITLE
Schéma des appels publics

### ISSUE THREAD

**Issue by jbledevehat** [etalab/schema.data.gouv.fr#221]
## Description du schéma des appels publics

Les appels publics sont des dispositifs de soutiens et d'aides pouvant prendre plusieurs forment : appels à projets, appels à manifestations d’intérêt, appels à communs, appels à candidatures, concours, programme d'accélération, dispositifs d'aides financières, dispositifs d'aides en ingénierie ou encore dispositifs de mécénat. Les appels publics sont plus généralement à destinations des collectivités, des entreprises, des associations, des organismes de recherche ou des administrations. 

Les appels publics peuvent avoir plusieurs finalités d'aide et/ou d'accompagnement. Par exemple les aides financières peuvent être des avances remboursables (et non uniquement des subventions). Autre exemple, les aides peuvent être une expertise en ingénierie technique ou administrative. A l'inverse, les aides peuvent parfois être transmises sans appels publics, comme par exemple les [aides exceptionnelles aux artisans et commerçants du CPSTI pendant la crise du COVID-19](https://aides-entreprises.data.gouv.fr/cpsti).

Principalement à destination de personnes morales, les appels publics peuvent être également à destination des citoyens (exemple avec l'[appel à candidature du programme EIG](https://eig.etalab.gouv.fr/participer/candidats/) ou le [programme d'accélération d'initiatives citoyennes](https://citoyens.transformation.gouv.fr/)). Les appels publics peuvent avoir une temporalité définie et ciblent l'ensembles des secteurs d'activités de la société.

Les appels publics produisent des lauréats (projets, recherches, initiatives, candidatures...) pouvant faire l'objet un autre schéma de données. 

## Liens utiles

-  [Vade Mecum des Aides d'Etat 2020](https://www.economie.gouv.fr/daj/vade-mecum-des-aides-detat-edition-2020)

### Exemples de sites ayant des appels publics :
- [aides-entreprises.fr](https://www.aides-entreprises.fr/)
- [aides-territoires.beta.gouv.fr](https://aides-territoires.beta.gouv.fr/)
- [economie.gouv.fr/plan-de-relance/appels-projets](https://www.economie.gouv.fr/plan-de-relance/appels-projets)
- [anil.org/aides-locales-travaux](https://www.anil.org/aides-locales-travaux/)
- [agirpourlatransition.ademe.fr/entreprises/aides-financieres/recherche](https://agirpourlatransition.ademe.fr/entreprises/aides-financieres/recherche)
- [mission-transition-ecologique.beta.gouv.fr](https://mission-transition-ecologique.beta.gouv.fr/)
- [cdcinvestissementsdavenir.achatpublic.com](https://cdcinvestissementsdavenir.achatpublic.com/accueil/)

## Stade d'avancement

Mon schéma est :
- [x] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [ ] **en construction :** ce schéma est en cours d'implémentation après son élaboration

`id`
`name`
`short_title`
`description`
`type` : appel à projets, appel à communs, appel à manifestation d'intérêt, appel à candidatures, concours...
`aid_types` : subvention, avance remboursable, ingénierie technique...
`perimeter` :  internationale, nationale, régionale, (Auvergne-Rhône-Alpes, Bourgogne-Franche-Comté...), départementale, EPCI...
`targeted_audiences` : association, collectivité, administration, entreprise, organisme de recherche...
`targeted_audiences_description`
`start_date`
`submission_deadline`
`predeposit_date`
`result_date`
`recurrence` : Ponctuelle, permanente
`subvention_rate_lower_bound`
`subvention_rate_upper_bound`
`contact`
`mail`
`instructors` : ADEME, MTE, DGE...
`taxonomy` (thématique, sous-thématique...)
`mobilization` : R&D, investissement...
`program_name` (ex : 4e Programme d'investissement d'avenir)
`program_logo` (url)
`program_acronym` (ex : PIA4)
`financers` : ADEME, BPI, Communauté de communes XY...
`fund` (ex : fond chaleur, fond qualité de l'air, fond économie circulaire...
`strategy` (ex : Stratégie nationale Hydrogène, Stratégie d'accélération économie circulaire...) 
`strategy_acronym`
`documents` (urls des annexes, guides...)
`origin_url`
`date_created`
`date_updated`

**Comment by geoffreyaldebert** [comment]
Merci @jbledevehat pour cette proposition de schéma.

Pour info à la communauté, depuis le message de Jean-Baptiste, deux réunions ont eu lieu en présence de différents acteurs :
- [ADEME](https://www.ademe.fr/), 
- [aides-territoires](https://aides-territoires.beta.gouv.fr/), 
- [CGDD](https://www.ecologie.gouv.fr/commissariat-general-au-developpement-durable-cgdd), 
- [Etalab](https://www.etalab.gouv.fr/), 
- [la région Bretagne](https://www.bretagne.bzh/) 

pour discuter de ce nouveau schéma en investigation.

Dans le cadre de ses activités, la start-up d'état aides-territoires possède déjà un template de fichier Excel utilisé pour récolter les données sur les appels à projets. Nous partons de celui-ci pour discuter, champs par champs, de l'utilité de l'information.

Nous avons ce jour passé en revue les premiers champs de ce template (partie "Présentation"), une prochaine session est prévue pour discuter des suivants. Le framadate : https://framadate.org/7MyLTBALjtAysavR 

N'hésitez pas à vous inscrire si vous souhaitez participer. 

Le fichier Excel en l'état est présent à [cette adresse](https://github.com/etalab/schema-appel-public/raw/master/SchemaAppelPublic.xlsx).

**Comment by geoffreyaldebert** [comment]
Il faudra également voir dans quelles mesures, ce schéma peut entrer en écho avec le schéma des subventions déjà existant https://schema.data.gouv.fr/scdl/subventions/ mais encore peu utilisé. Cc @jmbourgogne @johanricher

**Comment by jbledevehat** [comment]
Notre troisième réunion sera reporté et une nouvelle proposition de dates à travers un framadate a été partagé : https://framadate.org/9IZsd5kvi1Z8TWNL

**Comment by johanricher** [comment]
J'ai répondu concernant le référencement des "appels publics" dans les données subventions : https://git.opendatafrance.net/scdl/subventions/-/issues/9

Est-ce que le terme "appel public" correspond à un usage courant ou une définition officielle dans un texte règlementaire par exemple ? Dans le cas contraire je propose de trouver un terme plus explicite et sans ambiguïté. Il me semble en effet qu'au premier abord "appel public" laisse à penser qu'on parle d'appel téléphonique.

**Comment by jbledevehat** [comment]
Le terme "appel public" correspondant à un usage nouveau dans une logique de _design policies_ afin de parler des différents modes d'aides financière ou d'ingénierie. On est contre le changement de nom, l'idée étant de trouver un nom regroupant, les appels à projet, les appels à manifestations d'intérêt, les appels à communs, les appels à idées... Nommer tous cela "appels publics" a été le plus pertinent. Pour expliciter cela voici une [représentation de l'organisation des objets](https://i.ibb.co/WynCF9P/Schema-1-125x-3.png).

**Comment by jbledevehat** [comment]
Suite à nos derniers échanges voici la [proposition de la page descriptive des "Dispositifs d'aide"](https://pad.incubateur.net/4n3P16pwQ-CvtdeOv0NzPw) terme finalement partagé et validé par le groupe de travail.

**Comment by geoffreyaldebert** [comment]
Bonjour à tous,

Je vous informe que le schéma est publié sur schema.data.gouv.fr en version 0.0.1 : https://schema.data.gouv.fr/etalab/schema-dispositif-aide/ 🎉 

Merci à tous pour ce travail et spécialement à @jbledevehat pour la proposition initiale et le suivi de l'implémentation du schéma.

Je laisse cette issue ouverte quelques jours au cas où un acteur tiers souhaite intervenir, puis je la fermerai. N'hésitez pas à la rouvrir si vous en voyez l'intérêt.

**Comment by johanricher** [comment]
Bravo @jbledevehat @geoffreyaldebert ! :clap:
