### ISSUE TITLE
Spécifications des rapports de validation

### ISSUE THREAD

**Issue by slafayIGN** [etalab/schema.data.gouv.fr#232]
Bonjour,

Sauriez-vous où trouver les spécifications détaillés des rapports de validation de https://validata-api-dev.app.etalab.studio/apidocs ?

Il y a bien une valeur exemple dans les specs brutes : https://validata-api-dev.app.etalab.studio/apispec_1.json
mais il semble incomplet.

**Comment by johanricher** [comment]
Pour être sûr de comprendre le besoin : à quoi ressemblerait une spécification du rapport de validation ? Pouvez-vous me pointer en direction d'une ressource similaire sur un autre projet ?

**Comment by pprev94** [comment]
Bonjour,

La validation est faire par frictionless. le guide de validation est ici
https://framework.frictionlessdata.io/docs/guides/validation-guide

Par contre, je ne vois pas la différence entre report.errors et report.tasks[].errors

Cordialement
