### ISSUE TITLE
Schéma des données d'impact d'un service numérique public

### ISSUE THREAD

**Issue by restuccia** [etalab/schema.data.gouv.fr#241]
## Description du schéma
Etalab, en coopération avec beta.gouv.fr, envisage la mise en place d'un schéma commun pour les données d'impact des services numériques publiques. Ce schéma pourrait s'appliquer aux données d'impact des startups d'État dans un premier temps. L'objectif l'objectif est de fournir un cadre commun permettant de comparer facilement l'impact de différents services.

## Liens
[Guide de la performance - Direction du budget](https://www.budget.gouv.fr/documentation/fid-download/42519)
[Définir et mesurer l’impact - documentation de la communauté beta.gouv.fr](https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-gere-mon-produit-et-son-impact/definir-et-mesurer-limpact)

Exemples de statistiques d'impact :
- [datagir](https://datagir.ademe.fr/stats/)
- [mon-entreprise](https://mon-entreprise.urssaf.fr/stats)
- [Registre de Preuve de covoiturage](https://app.covoiturage.beta.gouv.fr/stats)

## Stade d'avancement

Mon schéma est :

- [x] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [x] **en construction :** ce schéma est en cours d'implémentation après son élaboration

**Comment by Pierlou** [comment]
closed with #284
