### ISSUE TITLE
Mise à jour du schéma dae

### ISSUE THREAD

**Issue by Fonaine** [etalab/schema.data.gouv.fr#244]
Bonjour,

Je souhaite mettre à jour le schéma dae. 
J'ai mis à jour le dépôt de référence avec un nouveau tag https://gitlab.com/arsante/atlasante/schema-dae/-/tags/1.0.4
mais je ne trouve plus la procédure pour actualiser cette référence sur schema.data.gouv qui pointe toujours sur la version 1.0.3
Merci d'avance pour votre aide,

**Comment by geoffreyaldebert** [comment]
Bonjour @Fonaine,

J'arrive peut-être après la bataille mais le schéma en v1.0.4 est publié sur schema.data.gouv.fr : https://schema.data.gouv.fr/atlasante/schema-dae/ 

Pour publier, il faut non seulement un tag mais aussi une release sur le repo du schéma.

Enfin, la mise à jour du site schema.data.gouv.fr s'effectue toutes les nuits donc les modifications ne sont visibles que le lendemain.

Je close l'issue mais n'hésitez pas à la rouvrir si besoin.
