### ISSUE TITLE
Lieux de médiation numérique

### ISSUE THREAD

**Issue by samgoeta** [etalab/schema.data.gouv.fr#249]
## Description du schéma
Il existe un réel besoin d’une vision nationale, complète et actualisée de l’offre de médiation numérique Des acteurs de la médiation numérique, notamment les hubs, ont produit de nombreuses données de recensement des lieux et des offres de médiation mais souvent, ces productions ne respectent pas le même format, rendant alors impossible une vision formalisée, complète et partagée de l’offre nationale de médiation numérique.

Pour répondre à cet enjeu d’harmonisation des données, la standardisation permettra la construction d’un nouveau standard décrivant l’offre de médiation numérique. Elle reposera sur un travail de concertation dans lequel des utilisateurs représentatifs définissent un schéma de données qui décrit le format des fichiers, les différents champs, les valeurs possibles…

En lien étroit avec ces travaux, l’ANCT mène actuellement un projet de cartographie nationale de l’offre de médiation numérique qui vise une première publication en mai 2022. Les données seront ouvertes pour développer une multitude d’usages : guider les usagers vers une structure de médiation numérique, accompagner les acteurs territoriaux dans le développement de l’offre, analyser l’adéquation entre l’offre et le besoin pour les publics fragiles…

Nous pourrons nous appuyer sur le [schéma développé par AidantsConnect](https://schema.data.gouv.fr/etalab/schema-inclusion-numerique/), aujourd’hui peu utilisé, pour construire ensemble un schéma plus simple et ancré dans les usages des acteurs de la médiation numérique. Ce travail est piloté par l’Agence nationale pour la cohésion des territoires (ANCT), La MedNum avec l’appui de Datactivist. La concertation autour du standard se structurera autour de cercles concentriques : un comité de pilotage proposera des arbitrages autour des suggestions d’un groupe ouvert de contributeurs.

## Liens

- Documentation complète des ateliers de conception sur Github : https://github.com/datactivist/standard-mediation
- Synthèse des ateliers à NEC sur le schéma de données des lieux de médiation numérique : https://numerique-en-communs.fr/exploration-donnees-territoires/

## Stade d'avancement

Mon schéma est :

- [x] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation

**Comment by geoffreyaldebert** [comment]
Bonjour Samuel,

Merci pour ta proposition. Ce sujet est effectivement porteur et je suis ravi de voir que vous avancez sur le sujet.

Je sais que vous êtes au courant mais France Tiers Lieux est également en train de mener une [initiative sur un schéma des Tiers Lieux](https://github.com/etalab/schema.data.gouv.fr/issues/179) en ce moment et cela serait pertinent que les deux schémas, qui partageront probablement des champs communs, soit fait de concert. Je crois comprendre que vous êtes aussi en lien avec [l'initiative autour des lieux d'insertion professionnelle](https://github.com/etalab/schema.data.gouv.fr/issues/206). Tout cela me semble aller sur la bonne voie.

A votre disposition si besoin d'avis technique, je participerai à l'un de vos ateliers avec plaisir.

Enfin, concernant le [schéma actuel](https://schema.data.gouv.fr/etalab/schema-inclusion-numerique/) et devant [le peu de donnée produites](https://www.data.gouv.fr/fr/datasets/?schema=etalab%2Fschema-inclusion-numerique) vis-à-vis de ces spécifications sur data.gouv.fr, je vous propose de le dé-publier de schema.data.gouv.fr en attendant que vos travaux aboutissent. Qu'en pensez-vous ?

Si c'est ok pour vous, je laisse quelque jours sous ce fil (mettons jusqu'à mardi 7 juin) avant de le dépublier au cas où cette dé-publication poserait problème à une personne de la communauté.

Bonne journée,

**Comment by EliseHPC** [comment]
Bonjour Geoffrey, 

Après plusieurs mois de concertation avec la communauté de la médiation numérique (la méthodologie et tous les ateliers sont documentés sur [l'espace github de La MedNum](https://github.com/LaMednum/standard-mediation-num) ) la première version du [schéma](https://github.com/LaMednum/standard-mediation-num/blob/main/Schema_V0.1.json) est désormais prête. 

Il me semble qu'il rempli les conditions pour être référencé sur schema.data.gouv.fr 
Sera-t-il possible de l'ajouter ? 

Merci d'avance, 
Bonne semaine

**Comment by geoffreyaldebert** [comment]
Bonjour Elise,
Super, c'est une bonne nouvelle de voir que ce schéma avance.

Plusieurs choses remarquées en clonant le repo : 
- il faudrait renommer le schéma porteur du schéma en schema.json
- il faudrait un fichier exemple valide en csv dans le repo (et l'indiquer dans le schéma)
- plusieurs exemples de champs du schéma ne sont pas valides (`services`, `publics_accueillis`, `labels_nationaux`, `modalites_accompagnement`) Il faudrait les corriger (je pense que c'est parce que votre contrainte en `enum` impose la sélection d'une seule possibilité et pas plusieurs)
- ce serait cool d'ajouter une CI sur le schéma pour avoir la visibilité tout de suite que le schéma est valide ou non
- il faudra par la suite faire une release du schéma sut github (en v0.1.0 du coup)

Tu peux m'ajouter en contributeur sur le schéma si tu veux et je peux m'occuper d'un ou plusieurs points ci-dessus. On peut également se faire un point audio si tu veux, n'hésite pas à me demander par mail.

Enfin, quid du sort de ce schéma : https://schema.data.gouv.fr/etalab/schema-inclusion-numerique/ En avez-vous parlé en groupe de travail ?

Pour ma part, je serai d'avis de le dé-publier devant les autres schémas en lien en cours ou déjà publié (tiers lieux, médiation numérique, insertion pro...). D'autre part, ce dernier n'est que très peu utilisé avec [une seule ressource](https://www.data.gouv.fr/fr/datasets/?schema=etalab/schema-inclusion-numerique) sur data.gouv.fr - qui de plus est invalide.

Bien à toi,
Geoffrey

**Comment by EliseHPC** [comment]
Geoffrey, 

Merci beaucoup pour tes retours ! J'ai bien renommé le schéma et ajouté des exemples. 

J'ai cependant deux questions : 
- Existe-t-il une contrainte pour permettre la sélection de plusieurs valeurs autorisées ? Ou la seule possibilité pour saisir plusieurs valeurs est de les séparer par une virgule et de les encadrer par des crochets et guillemets --> `(["valeur1","valeurs2"])` ? 
- Pourrais-tu m'aider pour l'ajout d'une CI ? Je ne maîtrise pas du tout... 

Je ne peux pas accéder aux paramètres pour t'ajouter en contributeur, sera-il possible de contribuer via des pulled requests ? 

Pour le schéma actuellement sur schema.dgf, il faudrait effectivement le dé-publier, le nouveau ayant vocation à le remplacer. 

Merci encore pour ton aide

**Comment by geoffreyaldebert** [comment]
Elise,

J'ai fais un fork et une PR [ici](https://github.com/LaMednum/standard-mediation-num/pull/5) qui prend en compte mes dernières remarques.

Pour finaliser la publication de ce schéma, il ne reste plus qu'à valider la PR, et créer une release sur le repo avec le nom `v0.1.0` (pour le tag et la release). Si tu as besoin d'aide pour le faire, n'hésite pas à me demander mais je n'ai pas les droits sur le repo, je ne peux pas le faire de mon côté.

Tiens-moi au courant et à bientôt,
Geoffrey

**Comment by EliseHPC** [comment]
Geoffrey, 

J'ai validé la PR et créé une release, donc tout devrait être bon. 
Merci encore pour ton aide. 

Bonne fin de journée, 
Elise

**Comment by geoffreyaldebert** [comment]
Super ! [Le schéma est publié](https://schema.data.gouv.fr/LaMednum/standard-mediation-num) 🎉 !

J'ai également dé-publié le précédent.

Bravo pour ce travail !
