### ISSUE TITLE
description des schémas relationnels de nos géostandards

### ISSUE THREAD

**Issue by rmitanch** [etalab/schema.data.gouv.fr#25]
Nous allons expérimenter le dépôt de schémas correspondant aux géostandards de la COVADIS
Nos schémas (à forte thématique métier) sont en général très relationnels, et il me paraît difficile de proposer un fichier pour chaque table, cela risque d'être très confus...

exemple : l'éolien terrestre (un seul géostandard) décrits deux regroupements logiques, le côté industrie d'une part avec 4 tables reliées (Parcs éoliens, éoliennes, autorisations, certificats éventuels), et le côté planification d'autre part, avec 2 tables également reliées (schémas régionaux, zones favorables)

J'ai déjà produit du code qui me convertit mon modèle UML (XMI 2.1 d'Enterprise Architect) vers une liste de schémas, et dans ce cas précis j'obtiens deux json

Eolien terrestre - industriel: une liste de 4 schémas (pour 4 tables)
Eolien terrestre - planification: une liste de 2 schémas (pour 2 tables)

_**Est-ce bien OK dans l'esprit de faire deux dépôts**, un premier pour l'industrie, le second pour la planification (et non pas un seul, ou pire 6) ?_

**Comment by AntoineAugusti** [comment]
Bonjour @rmitanch,

Merci d'avoir ouvert une issue. Dans quels formats sont vos schémas ? Nous [supportons depuis peu](https://github.com/etalab/schema.data.gouv.fr/issues/17#issuecomment-503079873) les dépôts qui contiennent plusieurs schémas au format XSD.

La documentation pour le format XSD est disponible en ligne : https://schema.data.gouv.fr/documentation/validation-schemas#validations-sp%C3%A9cifiques-au-format-xml-schema-definition-xsd.

On pourrait donc imaginer 2 dépôts (4 schémas), un pour l'industrie et le second pour la planification (2 schémas).

**Comment by rmitanch** [comment]
Bonjour @AntoineAugusti ,

Merci pour cette réponse

J'ai joint à titre d'illustration les schémas produits par mon proto - ils sont encore très imparfaits, car la documentation des schémas est très incomplète (il manque par exemple les champs author, contact, contributor, version, created, updated, homepage, uri, example) et du côté des champs du schéma je compte systématiser les champs example et type, voire constraints pattern
Si en dehors de ces défauts déjà identifiés il y a des remarques, je suis très preneur!

Sinon en réponse aux questions complémentaires 

- Les données sont en général publiées sur des Infrastructures de données géographiques nationales (GeoIDE) ou régionales
- Nous ne produisons nous-même aucune donnée, mais notre processus d'élaboration des géostandards tient compte aussi bien des problématiques de production locale de la donnée, d'échanges, et d'aggrégation et ou de rapportage national, en relation avec la Directive européenne INSPIRE
- Les utilisateurs sont en premier lieu les services déconcentrés de l'Etat, les collectivités territoriales, mais nous ne sommes pas forcément au courant de toutes les réutilisations possibles

P.S. pour info nous avons également expérimenté la production d'une description swagger/OpenAPI des données de nos géostandards, et je me demandais s'il y a un intérêt à diffuser également cette documentation connexe à nos standards - là également, je suis preneur des bonnes pratiques

[eolien_terrestre_v2.0.zip](https://github.com/etalab/schema.data.gouv.fr/files/3304928/eolien_terrestre_v2.0.zip)

**Comment by AntoineAugusti** [comment]
Bonjour,

Ces premiers jets de schémas me semblent prometteurs. L'ajout futur des contraintes me parait incontournable pour valider la qualité des données et pouvoir générer une documentation la plus pertinente possible : schema.data.gouv.fr génère automatiquement la documentation à partir des fichiers TableSchema.

Concernant la documentation OpenAPI, je vois un intérêt à la diffuser pour les éventuels intéressés. Ça peut être mentionné dans le README avec des liens vers les fichiers en question

**Comment by rmitanch** [comment]
Bonjour,
Merci pour ce retour : je suis tout à fait d'accord et considère qu'en tant que producteurs de géostandards, nous devons pour favoriser la réutilisation des données prendre en compte également la validation des données, et donc bien gérer les contraintes des schémas
J'attendrai donc d'avoir une réponse satisfaisante sur les contraintes avant de faire une première proposition de schémas
à très bientôt donc

**Comment by AntoineAugusti** [comment]
Bonjour,

Avez-vous du nouveau sur ce sujet ?

**Comment by rmitanch** [comment]
Bonjour,

pour être franc, je n'ai pas avancé du fait d'un calendrier assez 
chargé... je compte finaliser au plus tard début novembre, et je ne vois 
aucune difficulté technique a priori

A bientôt donc

Richard

**Comment by AntoineAugusti** [comment]
Bonjour,

Avez-vous des nouvelles concernant ce sujet ? Je peux clore la discussion pour le moment et vous pouvez créer une nouvelle discussion plus tard si nécessaire.
