### ISSUE TITLE
Schéma sur les aires de livraison

### ISSUE THREAD

**Issue by datagistips** [etalab/schema.data.gouv.fr#259]
Bonjour,

Dans la continuité des travaux d'OpenDataFrance et en partenariat avec elle, le Cerema avait travaillé, dans le cadre de [la Fabrique de la Logistique](https://www.lafabriquedelalogistique.fr/), à la standardisation des aires de livraison (https://opendatafrance.gitbook.io/fablog/groupes-de-travail/partage-des-donnees/zones-de-livraison)

Ce travail devrait continuer l'année prochaine en relation avec la DGITM.

Nous aimerions construire un schéma autour des aires de livraison en conviant les acteurs du territoire et professionnels du domaine désireux de participer au standard.

## Aires de livraison vs stationnement
Les aires de livraison présentent certaines différences avec les lieux de stationnement pour lesquels il existe [un schéma](http://schema.data.gouv.fr/etalab/schema-stationnement/). Le schéma sur les aires de livraison devrait comprendre des champs additionnels tels que le tonnage, le régime d'accès par exemple.

[Une première version du schéma est formalisée sur ce répertoire github](https://github.com/CEREMA/schema-aire-livraison)

## Un ensemble autour de la Logistique urbaine
Pour information, le Cerema a déjà produit le [schéma sur les arrêtés de circulation pour le transport de marchandises en ville](http://schema.data.gouv.fr/CEREMA/schema-arrete-circulation-marchandises/) et [la documentation associée](https://opendatafrance.gitbook.io/fablog/espace-arretes/accueil).

Nous envisageons de produire une documentation toute aussi dense, avec des éléments de compréhension et de méthodologie autour de la numérisation des aires de livraison.

Cet ensemble vise à améliorer la connaissance et la Logistique en ville.

Bien cordialement

- [x] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [ ] **en construction :** ce schéma est en cours d'implémentation après son élaboration

**Comment by Pierlou** [comment]
Bonjour, merci de porter ce nouveau schéma. Je vois sur votre repo que la structure est déjà bien avancée, où en êtes-vous dans votre démarche ?

**Comment by Pierlou** [comment]
Bonjour, cela nous convient parfaitement, nous attendons votre signal. N'hésitez pas à revenir vers nous d'ici là pour toute considération technique ou conceptuelle.

**Comment by datagistips** [comment]
Bonjour,

Nous avons avancé sur le schéma des aires de livraison : https://github.com/CEREMA/schema-aire-livraison

Pour le créer, nous nous sommes appuyés sur notre expertise locale en Logistique, sur la communauté FabLog, sur les travaux d'OpenDataFrance avec qui nous avons travaillé, ainsi que sur l'observation de jeux de données délivrés en OpenData.

Le voici : 

Ce schéma suit dans sa philosophie (noms des champs, etc...) le schéma pour numériser les arrêtés de circulation pour le transport de marchandises (https://schema.data.gouv.fr/CEREMA/schema-arrete-circulation-marchandises/)

Le schéma sur les aires de livraison comprend 21 champs (localisation, horaires et types d'intervention, référence d'arrêté, ...)

Nous avons créé en parallèle une version "ultra" du schéma comprenant des champs additionnels, pour des informations additionnelles avec des informations sur la signalisation, les équipements : https://github.com/CEREMA/schema-aire-livraison/blob/main/schema-ultra.json

Quelle serait la bonne pratique dans le cas présent par rapport à ce schéma avancé ? Les champs du profil ultra devraient-ils rejoindre le schéma standard ?

Sachant qu'un nombre très élevé de champs est parfois critiqué pour les personnes chargées d'éditer des données, des réflexions sur différents profils d'édition (par profondeur d'information, par usage,...) est-elle en réflexion ? Sachant qu'il s'agit entre autres, selon moi, d'un problème associé aux interfaces d'édition.

Pourriez-vous me dire si le repo est ok pour une publication dans le trimestre ? Nous vous donnerons le feu vert.

**Comment by Pierlou** [comment]
Bonjour,

Merci pour ce travail de qualité, je vous confirme que le schéma est bien valide en l'état (ainsi que le fichier d'exemple), et que le repo est bien structuré comme attendu. Il manque cependant une release pour pouvoir le référencer sur (preprod.)schema.data.gouv. Nous avons l'habitude d'utiliser la nomenclature SemVer, donc ici le schéma pourrait être en v0.1.0 par exemple.

Concernant la version "ultra" du schéma, je ne suis pas sûr qu'en l'état elle soit bien interprétée ni utilisée, car elle ne sera pas référencée sur schema.data.gouv. Je vois deux options possibles : 
- si vous pensez que la valeur ajoutée des champs additionnels est conséquente, il pourrait être plus intéressant de faire de la version "ultra" la version de base, en ajustant le caractère `required` des champs en conséquence. Comme vous le mentionnez, la complexité du schéma (notamment liée à son nombre de champs) peut-être rédhibitoire pour ls producteurs, surtout si la production de données se fait manuellement. A voir selon les moyens mis à disposition des producteurs, et une potentielle contrainte légale (comme pour les [IRVE](https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000043475441) par exemple)
- si la complexité est trop grande avec les champs "ultra" et/ou que vous pensez que le schéma "de base" suffit, vous pouvez laisser le repo tel quel, en gardant bien en tête que la version "ultra" ne sera pas vraiment visible. NB : si un fichier est valide pour un schéma MAIS contient des colonnes additionnelles, il est considéré comme "partiellement valide" par nos outils, notamment validata.fr. Il sera donc possible de pousser pour l'utilisation des champs "ultra", mais s'ils sont utilisés, autant qu'ils soient dans le schéma de base je pense.

**Comment by datagistips** [comment]
Bonjour,

Nous avons pris des champs de la version maximaliste du schéma pour la version standarde et ajouté des champs liés à l'obligation de disposer d'un disque (INTERV_DISQUE), à la présence d'un débattement de part et d'autre de l'aire (EMPRISE_DEBATTEMENT) et un champ sur le stationnement Chaussée, Trottoir, etc... (STATIONNEMENT_LOCALISATION).

Nous avons changé le champ INTERV_DUREE en format duration. Est-il bien pris en charge par publier.etalab.studio ou faut-il préférer time ?

Nous avons ajouté le script de test du schéma automatisé dans `.github`

Voici le schéma : https://github.com/CEREMA/schema-aire-livraison

Est-ce OK pour vous ?

**Comment by Pierlou** [comment]
Bonjour,
Merci pour ces avancées. Tout semble OK pour la publication, à l'exception du tag comme mentionné plus haut : nous avons l'habitude d'utiliser la nomenclature SemVer, donc ici le schéma pourrait être en v0.1.0 par exemple. Cette correction faite, nous pourrons ajouter le schéma à schema.data.gouv.fr 🚀

**Comment by datagistips** [comment]
Bonjour, c'est bon 
Voici la première release : https://github.com/CEREMA/schema-aire-livraison/releases/tag/v0.1.0

**Comment by Pierlou** [comment]
Le voilà publié : https://schema.data.gouv.fr/CEREMA/schema-aire-livraison/ ! 🎉

**Comment by Pierlou** [comment]
Je viens de voir que la version n'a pas été modifiée en même temps que le reste : https://github.com/CEREMA/schema-aire-livraison/blob/fc00f07ae1761b118b1282e6b6f6c8f479b2ec2c/schema.json#L66. A voir si vous souhaitez corriger ça maintenant (en faisant une nouvelle release ou en effaçant la release et en corrigeant avant de la recréer), ou si cela attendra la version suivante.
Nous travaillons sur un script qui permettra d'éviter ces désagréments : https://github.com/etalab/tableschema-template/pull/8, vous pourrez l'ajouter à ce repo si vous le souhaitez

**Comment by datagistips** [comment]
Merci pour le signalement :)
Je viens de remplacer la release : https://github.com/CEREMA/schema-aire-livraison/blob/v0.1.0/schema.json#L66
Je viens d'intégrer le script assert_version.yml au `.github`

**Comment by datagistips** [comment]
**Objet : jours et horaires de livraison**

Bonjour,

Petite question : le Cerema travaille, dans le cadre de **Digilog**, à une amélioration du schéma sur les aires de livraison.
Un champ décrit les jours et heures de livraison autorisées.

Précédemment, le format **Opening Hours** était employé car bénéficiant d'une large communauté d'utilisateurs, par ex. **OSM**, et potentiellement de récupérer depuis OSM les attributs d'horaires associés aux aires de livraison renseignées dans la base ouverte. 

Egalement, on trouve des **IHM** en ligne permettant aux agents de transcrire facilement leurs specs de jours, horaires en chaîne Opening Hours.

UrbanRadar, avec qui le Cerema travaille, suggère d'utiliser plutôt le formatage associé aux **[Curbs Data Specification](https://github.com/openmobilityfoundation/curb-data-specification)**, par ex.
`string ([{"days_of_week":["ddd","ddd"],"times_of_day":[{"from":"HH:MM","to":"HH:MM"}]}])`

Cela implique de renseigner du **JSON** dans un champ. De mon point de vue, cela augmente le niveau de technicité et la rigueur employés lors du remplissage.

D'un autre côté, il s'agit d'un format qui a fait consensus dans la communauté logistique.

Ce format est aussi associé au fait que les données CDS sont en **JSON** à la base. Le schéma, lui, vise la donnée **tabulaire**.

Auriez-vous un avis sur la question ?
