### ISSUE TITLE
Schéma sur les zones d'activités économiques

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [etalab/schema.data.gouv.fr#273]
## Description du schéma
Une **zone d'activités économiques (ZAE)** est réservée à l’implantation d’entreprises.
Elle réunit les pouvoirs publics, les collectivités et les entreprises dans une logique partenariale autour d’objectifs de croissance.
Elle est en général placée sous le régime juridique du permis d'aménager ou d'une zone d'aménagement concerté (ZAC).

On dénombre un peu plus de **30 000 ZAE** couvrant environ **500.000 ha** du territoire national.

**Depuis la [loi NOTRe](https://www.ecologie.gouv.fr/loi-portant-sur-nouvelle-organisation-territoriale-republique-notre), les ZAE relèvent de la compétence de l’EPCI.**

La Loi Climat et Résilience a, parmi ses mesures de lutte contre l'artificialisation des sols, engendré l'article [L.318-8-2](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043968275) du code de l'urbanisme. Celui-ci prévoit que **l’autorité compétente de ZAE établisse un inventaire foncier tous les six ans qui comporte un état parcellaire des unités foncières composant la ZAE, l'identification de ses occupants, et le taux de vacance de la ZAE. Cet inventaire devra être établi d'ici août 2023 et sera transmis à l’autorité compétente en matière de SCOT, de document d’urbanisme et de PLH.**

Ainsi émergent les besoins de :
- **Répertorier** urgemment les sites économiques et les ZAE sur l'ensemble du territoire ;
- **Développer l’approche foncière des ZAE** afin de suivre la commercialisation des parcelles, et connaître leur rythme de consommation foncière.

Des démarches de standardisation locales remarquables ont déjà été effectuées : le [GT ZAE de ](https://ideo.ternum-bfc.fr/groupes-projets/groupe-zones-dactivites-economiques)[IdéoBFC](https://ideo.ternum-bfc.fr/groupes-projets/groupe-zones-dactivites-economiques) a élaboré le [Guide méthodologique pour la standardisation des sites économiques](https://ideo.ternum-bfc.fr/sites/default/files/2022-09/IDEO%20BFC%20Guide%20m%C3%A9thodologique%20sites%20%C3%A9conomique%20v.2.1%20Juillet%202022_0.pdf), la DDT69 a développé l'observatoire zones d'activités économiques du Rhône ([OZAR](https://www.rhone.gouv.fr/index.php/Politiques-publiques/Economie-travail-et-emploi/Zones-d-activites-economiques/Observatoire-des-Zones-d-Activites-Economiques-du-Rhone-OZAR)) et le Cerema œuvre à l'automatisation du repérage des emprises d'activités et à l'intégration des ZAE dans l'outil d’analyse et de prospective sur le foncier [Urbansimul](https://urbansimul.cerema.fr/).

Il apparaît désormais nécessaire d'**homogénéiser au niveau national le recensement et la qualification des ZAE** pour assurer une meilleure coordination des multiples acteurs de l'aménagement du territoire.

Le **GT CNIG Aménagement** *(du territoire)* a été  [mandaté](http://cnig.gouv.fr/IMG/pdf/230119_mandat_gt_cnig_amenagement.pdf) par la [Commission des standards du CNIG](http://cnig.gouv.fr/commission-des-standards-a640.html) pour élaborer en coordination avec Etalab le futur **géostandard national des Zones d'activités économiques**. 

Ce groupe de travail a été lancé en mars 2023, il est ouvert à toutes participations.
Le Github du projet est : https://github.com/cnigfr/schema-sites-economiques

## Liens
- [loi NOTRe](https://www.ecologie.gouv.fr/loi-portant-sur-nouvelle-organisation-territoriale-republique-notre)
- article [L.318-8-2](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000043968275) du code de l'urbanisme
- [Guide méthodologique pour la standardisation des sites économiques](https://ideo.ternum-bfc.fr/sites/default/files/2022-09/IDEO%20BFC%20Guide%20m%C3%A9thodologique%20sites%20%C3%A9conomique%20v.2.1%20Juillet%202022_0.pdf)
- [Observatoire zones d'activités économiques du Rhône (OZAR)](https://www.rhone.gouv.fr/index.php/Politiques-publiques/Economie-travail-et-emploi/Zones-d-activites-economiques/Observatoire-des-Zones-d-Activites-Economiques-du-Rhone-OZAR)

## Stade d'avancement

Le schéma est :

- [ ] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [ ] **en consultation :** l'appel à commentaires CNIG (consultation publique) est en cours
- [ ] **en construction :** ce schéma est en cours d'implémentation après son élaboration

**Comment by Pierlou** [comment]
Bonjour, merci de porter ce nouveau schéma. Vous commencez à être coutumiers des processus, n'hésitez pas à nous solliciter si besoin.

**Comment by GT-CNIG-DDU** [comment]
Le [GT CNIG Aménagement / sous-groupe ZAE](https://cnig.gouv.fr/gt-friches-a25940.html#H_Sous-groupe-ZAE) a validé le [projet de standard "Site Economique"](https://github.com/cnigfr/schema-sites-economiques/tree/main/standard).

Ceci le rend éligible à l'appel à commentaires CNIG (consultation publique), qui sera lancé mi-septembre.

**Comment by GT-CNIG-DDU** [comment]
Le [géostandard CNIG Sites Economiques v2023-10](https://cnig.gouv.fr/ressources-am%c3%a9nagement-a26047.html) a été validé par la Commission CNIG des Standards du 27 octobre.

Ce standard d'échange de données présente la particularité d'avoir fait  l'objet d'une coordination étroite entre le CNIG et schema.data.gouv.fr.

Il présente quatre classes d'objets (au lieu d'une, par exemple dans le standard Friches) ce géostandard est le premier à utiliser le concept de "Data package", qui permet de regrouper plusieurs schémas (en l'occurrence 4) concourant à décrire une même thématique (Site Economique).

Le géostandard permettra d'alimenter en données le [Portail national du foncier économique](https://www.cerema.fr/fr/actualites/portail-national-foncier-economique-acteurs-co-construit) dont l’ouverture est prévue début 2024 dans une version 0 « Produit Minimal Viable ».

La thématique Sites Economiques bénéficie ainsi d'une intégration totale entre la documentation sur la méthodologie d'inventaire des zones d'activités économique (ZAE) ; la standardisation de l'échange des données ; la prochaine plateforme nationale ; et les outils d'édition et de publication de données ouvertes.

Le géostandard sera très probablement amené à évoluer en fonction de l'expression des besoins de sa communauté d'utilisateurs et de son écosystème technique applicatif.
