### ISSUE TITLE
Améliorer le CSS des schéma

### ISSUE THREAD

**Issue by fchabouis** [etalab/schema.data.gouv.fr#275]
Bonjour,

Je trouve que la présentation du texte sur le site pourrait être améliorée, en particulier les espaces entre les différents éléments HTML, qui rendent actuellement la lecture du contenu moins agréable et claire qu'elle ne pourrait l'être.

![image](https://user-images.githubusercontent.com/15341118/219331558-7e4b64aa-096e-4366-a1c3-a83ba68d8bf9.png)

![image](https://user-images.githubusercontent.com/15341118/219331903-6886a709-634a-4cf4-ac77-80a0b6c115a4.png)

copies d'écran prises sur https://schema.data.gouv.fr/etalab/schema-irve-statique/2.2.0/documentation.html

**Comment by Pierlou** [comment]
Bonjour, j'ai fait quelques modifs dans ce sens : https://github.com/etalab/schema.data.gouv.fr/pull/279
