### ISSUE TITLE
Erreurs par e-mail toutes les 48h

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/schema.data.gouv.fr#29]
Actuellement si les erreurs de validation ne sont pas corrigées, on envoie un e-mail de rappel toutes les 48h.

Vous avez dû recevoir pas mal d'e-mails @CharlesNepote @johanricher et je m'en excuse. Je suis étonné que n'ayez pas râlé.

Comment faire mieux ? Je pense que c'est pertinent d'envoyer ces rappels seulement si l'erreur concerne la dernière version. Si ce sont d'anciennes versions, inutile de penser que les producteurs peuvent corriger ça.

**Comment by johanricher** [comment]
Je n'ai pas reçu d'email. Quelles sont les erreurs de validation en question ?

**Comment by AntoineAugusti** [comment]
Tu peux regarder par exemple https://circleci.com/gh/etalab/schema.data.gouv.fr/2752 dans la tâche "Fetch remote repositories"

**Comment by johanricher** [comment]
Les notifications sont envoyées où ?

**Comment by AntoineAugusti** [comment]
Aux adresses déclarées dans https://github.com/etalab/schema.data.gouv.fr/blob/master/aggregateur/repertoires.yml. Donc normalement `scdl@opendatafrance.email`

**Comment by johanricher** [comment]
Ah oui ok je comprends. On (Jailbreak) n'a pas accès à cette boîte, c'est pour ça que le spam nous a été épargné. :)

**Comment by AntoineAugusti** [comment]
J'ai fait en sorte que les e-mails de rappels ne soient pas envoyés à info@data.gouv.fr pour ne pas se faire spammer tous les 2 jours pour les anciennes versions de schémas invalides.

Peut-être que cette fonctionnalité de rappel n'est pas nécessaire ou qu'il faut la revoir. @abulte, un avis ?

**Comment by abulte** [comment]
> Je pense que c'est pertinent d'envoyer ces rappels seulement si l'erreur concerne la dernière version. Si ce sont d'anciennes versions, inutile de penser que les producteurs peuvent corriger ça.

Ca me parait être une bonne idée 💡

**Comment by AntoineAugusti** [comment]
Avec la PR ci-dessus, le problème devrait être corrigé

**Comment by CharlesNepote** [comment]
Super l'idée des emails d'alerte, mais celui que j'ai reçu était peu cryptique :
```Bonjour !

Des erreurs sont survenues lors de la validation de vos schémas.

- InvalidVersionException: [repo `CharlesNepote/liste-prenoms-nouveaux-nes` no tag]: Version is invalid: 0.5beta.0

Merci de corriger ces erreurs.
```

0.5beta0 est en effet une vieille version. J'ai adopté le versionnement sémantique depuis pas mal de temps. Merci de me dire s'il y a d'autres choses à faire.

Bon je me suis bien douté que tout ça venait de vous (grace à l'adresse), mais un peu plus de contexte dans le mail d'alerte aiderait un peu ;-)
* l'URL du schema que vous tentez de valider
* si c'est possible le lien vers une page où on peut rejouer le contrôle pour vérifier qu'on a bien corrigé
* une signature et un lien vers schema.data.gouv.fr

Au passage, bravo pour tout le boulot déjà réalisé, c'est utile !

**Comment by AntoineAugusti** [comment]
> Merci de me dire s'il y a d'autres choses à faire.

Je te confirme que non, surtout que les versions suivantes sont bien valides et donc intégrées automatiquement.

Cet e-mail est clairement améliorable. Je vais essayer d'améliorer ceci.
