### ISSUE TITLE
Ajouter un titre dans `schemas.json`

### ISSUE THREAD

**Issue by abulte** [etalab/schema.data.gouv.fr#34]
Pour l'intégration à https://github.com/etalab/csv-gg, ce serait bien d'avoir un champ `title` ou autre avec le nom "humain" du schéma dans https://schema.data.gouv.fr/schemas/schemas.json pour remplir la liste déroulante de choix du schéma. Et pourquoi pas une `description` si on ajoute un champ ℹ️ un jour ?

Le problème est que ça ne respecte pas le schéma https://framagit.org/opendataschema/catalog/blob/master/schema-catalog.json... On ouvre une PR là-bas ?

**Comment by AntoineAugusti** [comment]
Ça me parait être une bonne idée. Comment fait Validata sans ces 2 éléments actuellement ? C'est croisé avec un autre fichier ?

Ça parait incontournable d'afficher ceci dans l'interface.

Tu veux bien te charger de la PR là-bas ?

**Comment by abulte** [comment]
> Comment fait Validata sans ces 2 éléments actuellement ? C'est croisé avec un autre fichier ?

Je n'ai pas vérifié mais je pense qu'il tire les infos du schéma après l'avoir "téléchargé". Ca parait un peu bancale sur une SPA.

J'ai vu aussi que le `name` n'était pas (plus) obligatoire là-bas https://framagit.org/opendataschema/catalog/blob/master/schema-catalog.json, ce qui est embêtant pour nous.

> Tu veux bien te charger de la PR là-bas ?

Allez.

**Comment by abulte** [comment]
> Je n'ai pas vérifié mais je pense qu'il tire les infos du schéma après l'avoir "téléchargé". Ca parait un peu bancale sur une SPA.

En même temps ça permet de ne pas dupliquer les infos... Mais ça implique de dupliquer la logique de fetch du schéma 🤔

**Comment by AntoineAugusti** [comment]
On peut avoir des clés supplémentaires non requises de notre côté après uniquement.

**Comment by AntoineAugusti** [comment]
On a accès à ces métadonnées : https://github.com/etalab/schema.data.gouv.fr/blob/master/web/_data/schemas.yml

Tu vois des choses supplémentaires requises ?

**Comment by abulte** [comment]
https://framagit.org/opendataschema/catalog/issues/1

**Comment by AntoineAugusti** [comment]
Ils ont mergé là-bas :)
