### ISSUE TITLE
gabarit d’URL/URI suivant RFC 6570

### ISSUE THREAD

**Issue by ele-gall-ac-mineducation** [etalab/schema.data.gouv.fr#40]
utiliser le standard officiel RFC 6570 pour spécifier les exemples de gabarits d’URI/URL : 

https://schema.data.gouv.fr/documentation/integration-autres-systemes#urls-stables

https://tools.ietf.org/html/rfc6570

syntaxe /{variable}/ plutôt que /:variable/

Exemple d’utilisation par la Dila sur légifrance pour ELI (European Legislative Identifier) :

http://www.eli.fr/fr/constructionURI.html

**Comment by abulte** [comment]
Bonjour,

Merci pour cette suggestion. Pourriez-vous éventuellement proposer une Pull-Request avec les changements ? Vous devriez pouvoir la faire directement depuis l'interface de Github.

**Comment by ele-gall-ac-mineducation** [comment]
C’est fait, avec un rechercher-remplacer par expressions rationnelles/régulières sur le bloc url_stables :

(?<=[^[:alnum:] ]):([:[:alnum:]_]*)
→
{\1}
