### ISSUE TITLE
Site web

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/schema.data.gouv.fr#5]
Le titre de ce dépôt laisse envisager que ceci correspond à un site web, accessible à l'adresse https://schema.data.gouv.fr, qui n'existe pas pour le moment.

Est-il prévu d'en avoir un ?

**Comment by abulte** [comment]
C'est prévu 🤗

**Comment by AntoineAugusti** [comment]
Ping moi si je peux aider

**Comment by abulte** [comment]
On va déjà se mettre d'accord sur la structure #4 et puis on pourra faire une première version je pense 💪 L'idée c'était de rassembler un peu de contenu dans les README du repo, ce qui est à peu près le cas.

**Comment by noirbizarre** [comment]
Oui, normalement si tu as les README déjà, avec github pages ou Jekyll, t'as déjà une base de site.
Après la structure choisie en #4 permettra de facilement itérer ici.

**Comment by AntoineAugusti** [comment]
Ça sort rapidement. Je ferme.
