### ISSUE TITLE
Ajouter une référence au SANDRE

### ISSUE THREAD

**Issue by abulte** [etalab/schema.data.gouv.fr#53]
Le SANDRE fait un travail assez similaire au nôtre mais dans le domaine des données sur l'eau http://www.sandre.eaufrance.fr. Je pense qu'il serait opportun d'y faire référence afin :
- de faire connaitre cette initiative à celles et ceux qui s'intéressent aux schémas de données
- de montrer que nous avons connaissance de cette initiative et que nous ne dupliquons pas un effort existant

Un § "Initiatives similaires" sur la home me parait tout indiqué.

WDYT?

**Comment by abulte** [comment]
http://id.eaufrance.fr/ddd/vic

**Comment by AntoineAugusti** [comment]
Ça m'a l'air d'être une bonne idée. Tu ferais une petite PR ? 🙏

**Comment by abulte** [comment]
https://giphy.com/gifs/know-monty-python-nudge-13vPE0A3DPqOcg
