### ISSUE TITLE
Utilisation du standard W3C "CSV on the Web"

### ISSUE THREAD

**Issue by benoitdavidfr** [etalab/schema.data.gouv.fr#54]
Bonjour,

Le W3C a adopté comme recommandation le standard [CSV on the Web](https://www.w3.org/TR/tabular-data-primer/). Il me semble que ce standard s'est inspiré de Table Schema. Il semblerait préférable pour définir les échanges de données publiques d'utiliser un standard recommandé par le W3C et pris en compte par les moteurs de recherche. Avez-vous prévu de prendre en compte ce type de schéma ?

Cordialement

Benoit DAVID
Ministère de la transition écologique

**Comment by abulte** [comment]
Bonjour,

Effectivement CSVW a certains avantages indéniables. 

Toutefois nous avons choisi de commencer avec TableSchema parce que l'écosystème était plus actif autour de ce format (schémas déjà existants, outils comme https://go.validata.fr et de https://frictionlessdata.io), probablement parce que ce format est plus facile à prendre en main.

Rien n'empêche de supporter la déclaration de schémas CSVW sur schema.data.gouv.fr, l'initiative n'est pas dépendante d'un format en particulier. Nous supportons déjà XSD et JsonSchema par exemple.

Si vous connaissez un schéma au format CSVW qui mériterait d'être référencé sur schema.data.gouv.fr, cela peut être l'occasion de travailler sur son intégration.

**Comment by johanricher** [comment]
> Il semblerait préférable pour définir les échanges de données publiques d'utiliser un standard recommandé par le W3C et pris en compte par les moteurs de recherche.

Pour un bon SEO c'est ça qu'il faut respecter : https://schema.org/Dataset. C'est ce que fait déjà Data.gouv.fr par exemple (@noirbizarre) ([Google Dataset Search](https://toolbox.google.com/datasetsearch) est un bon moyen de tester). La façon dont sont structurées les données sous-jacentes n'est pas vraiment déterminante.

Sinon, pour tout le reste, ce qui fait un standard c'est l'usage pas l'autorité. En l'occurence, comme l'a rappelé Alexandre, pour l'instant Table Schema a l'avantage.
