### ISSUE TITLE
exemple de texte réglementaire publiant un schema

### ISSUE THREAD

**Issue by benoitdavidfr** [etalab/schema.data.gouv.fr#57]
Bonjour,
Je suis sollicité sur la rédaction d'un décret et d'un arrêté portant application de l’article L163-5 du code de l’environnement qui prévoie la mise en place d'un système national d'information géographique des mesures de compensation des atteintes à la biodiversité.
Dans ce cadre, j'envisage que les données demandées aux maitres d'ouvrage soient structurées en GeoJSON conformément à un schéma JSON.
Avez-vous des recommandations sur la manière de rédiger le décret et l'arrêté ?
Le schéma JSON doit-il être publié dans l'arrêté ?
Avez-vous des exemples de telles publications ?
Merci d'avance.

Benoit DAVID - MTES/CGDD

**Comment by AntoineAugusti** [comment]
Bonjour M. David,

Merci pour votre message. Nous référençons les différents arrêtés réglementaires définissant des modèles de données dont nous avons connaissance sur une page dédiée : https://schema.data.gouv.fr/documentation/schemas-reglementaires.

Un exemple pertinent peut être l'arrêté de la [commande publique](https://www.legifrance.gouv.fr/jo_pdf.do?id=JORFTEXT000034492587). Je référence @ColinMaudry qui connait bien ce sujet et qui aura peut-être un avis sur ce qui pourrait être amélioré dans cet arrêté.

Après en avoir discuté avec mon collègue @abulte, voici ce que nous recommandons pour vos questions.

> Dans ce cadre, j'envisage que les données demandées aux maitres d'ouvrage soient structurées en GeoJSON conformément à un schéma JSON.
Ceci nous parait tout à fait adapté. Le format peut être précisé dans un article de l'arrêté.

> Avez-vous des recommandations sur la manière de rédiger le décret et l'arrêté ?
Comme indiqué précédemment, je vous recommande la lecture de la page https://schema.data.gouv.fr/documentation/schemas-reglementaires

> Le schéma JSON doit-il être publié dans l'arrêté ?
Nous pensons que ce n'est pas pertinent. Une telle publication ne permet pas une intégration immédiate par des équipes techniques. Ce n'est également pas très souple, car si le schéma devait évoluer de manière infime (ajustements des descriptions, corrections mineures), il faudrait un nouveau texte réglementaire. Je pense que vous pourriez introduire dans les textes réglementaires un lien vers le site schema.data.gouv.fr en précisant que le schéma de données dans sa dernière version est toujours disponible là-bas, avec un historique des changements, de la documentation et un point de contact.

> Avez-vous des exemples de telles publications ?
Répondu précédemment.

Au plaisir d'échanger

**Comment by AntoineAugusti** [comment]
Bonjour @benoitdavidfr,

Est-ce que ces éléments ont pu vous aider ?

**Comment by ColinMaudry** [comment]
Concernant l'arrêté sur la publication des données de la commande publique, nous n'avons pas eu de soucis de ce côté là. Je pense qu'effectivement, à l'époque, il manquait un site gouvernemental dédié aux schémas. On a référencé un dataset sur data.gouv.fr, mais ce n'est pas idéal.

**Comment by abulte** [comment]
Faute d'activité, je ferme cette _issue_. N'hésitez pas à la rouvrir si besoin.
