### ISSUE TITLE
Description des schémas des géostandards CNIG d'urbanisme

### ISSUE THREAD

**Issue by Arnogal** [etalab/schema.data.gouv.fr#59]
Bonjour,

J'anime le groupe de travail CNIG sur la dématérialisation des documents d'urbanisme http://cnig.gouv.fr/?page_id=2918

Je souhaiterais tester la description des géostandards CNIG d'urbanisme, en commençant par le géostandard PLU : http://cnig.gouv.fr/?page_id=2732, qui est à la fois un géostandard d'usage (GPU...) et réglementaire _(Ordonnance du 19 décembre 2013 relative à l'amélioration des conditions d'accès aux documents d'urbanisme et aux SUP)_

N'étant pas encore familiarisé avec schema.data.gouv.fr, par où commencer ?
Arnauld

**Comment by AntoineAugusti** [comment]
Bonjour,

Merci pour votre question.

> N'étant pas encore familiarisé avec schema.data.gouv.fr, par où commencer ?
Je vous conseille de lire tout d'abord les différentes pages de documentation, accessibles depuis le menu à gauche sur https://schema.data.gouv.fr. Vous y trouverez des explications sur le projet, les standards supportés pour le moment, les démarches à suivre pour ajouter un schéma.

Si la transcription de vos différents schémas est une démarche longue et couteuse, il est possible que nous fassions plutôt un renvoi vers votre site web, comme fait préalablement pour le SANDRE https://github.com/etalab/schema.data.gouv.fr/issues/53 et [en ligne](https://schema.data.gouv.fr/#sandre).

À votre disposition pour toute précision.

**Comment by abulte** [comment]
Faute d'activité, je ferme cette _issue_. N'hésitez pas à la rouvrir si besoin.
