### ISSUE TITLE
[irve] renommer le champ "accessibilité" en "accessibilite" ?

### ISSUE THREAD

**Issue by pierredittgen** [etalab/schema.data.gouv.fr#6]
Dans le schéma proposé, les accents dans les noms de champ ont été retirés, ex :
- n_amenageur
- n_operateur
- acces_recharge

sauf pour le champ "accessibilit[é]".

Ceci pose problème lors de la validation par la brique logicielle goodtables-py utilisé par Validata. Serait-il possible de renommer cet en-tête de colonne en "accessibilite" ?

**Comment by abulte** [comment]
D'autre part, goodtables a l'air de fonctionner avec ce nom de colonne, cf http://goodtables.io/github/etalab/schema.data.gouv.fr/jobs/34.

**Comment by loichay** [comment]
Il existe des contre-exemples pour lesquels des schémas ont été modifiés sans que les modifications soient répercutées dans les textes : 

- Séparateur pour les champs `montant` `nature` et `pourcentageSubvention` pour le [format des subventions](https://github.com/etalab/format-subventions#110) fixé par [arrêté](https://www.legifrance.gouv.fr/jo_pdf.do?id=JORFTEXT000036040528)

- Ajout d'un champ optionnel `uid` pour le [format des marchés publics](https://github.com/etalab/format-commande-publique#notes-de-version) fixé par [arrêté](https://www.legifrance.gouv.fr/jo_pdf.do?id=JORFTEXT000037282994)

**Comment by pierredittgen** [comment]
> D'autre part, goodtables a l'air de fonctionner avec ce nom de colonne, cf http://goodtables.io/github/etalab/schema.data.gouv.fr/jobs/34.

@abulte Le problème doit alors se situer dans notre intégration. Merci pour le test

**Comment by abulte** [comment]
En effet @loichay.

Toutefois il me semble :
- que le point sur les séparateurs des subventions était bloquant pour obtenir un CSV valide
- qu'ajouter un champ optionnel est une autre question

Ce qui m'embête beaucoup si on change le nom de colonne c'est que quelqu'un qui suit le format de l'arrêté en produisant par ailleurs un CSV parfaitement valide (et il y en a déjà) verra son fichier rejeté.

**Comment by pierredittgen** [comment]
@abulte Le problème d'encodage a été corrigé chez nous.

Le validateur IRVE est [en ligne sur Validata](https://go.validata.fr/validators/scdl-irve)

Attention : dans le fichier schema.json, les propriétés `required` doivent apparaître dans comme une clef du dictionnaire `constraints`.

**Comment by abulte** [comment]
@pierredittgen super nouvelle !

Merci pour le point sur `required`, j'ouvre une nouvelle issue et je corrige ça.
