### ISSUE TITLE
descriptif erroné dans le schéma des équipements

### ISSUE THREAD

**Issue by ele-gall-ac-mineducation** [etalab/schema.data.gouv.fr#60]
Bonjour, 

Au vu de la description de la longitude :

[https://github.com/etalab/schema.data.gouv.fr/blob/c7e164de79e5228f6135e5a56f37a8c976218a50/aggregateur/data/scdl/equipements/0.1.0/schema.json#L185](https://github.com/etalab/schema.data.gouv.fr/blob/c7e164de79e5228f6135e5a56f37a8c976218a50/aggregateur/data/scdl/equipements/0.1.0/schema.json#L185)

celle de la latitude parait erronée :
 
[https://github.com/etalab/schema.data.gouv.fr/blob/c7e164de79e5228f6135e5a56f37a8c976218a50/aggregateur/data/scdl/equipements/0.1.0/schema.json#L195](https://github.com/etalab/schema.data.gouv.fr/blob/c7e164de79e5228f6135e5a56f37a8c976218a50/aggregateur/data/scdl/equipements/0.1.0/schema.json#L195)

Merci.

**Comment by AntoineAugusti** [comment]
Bonjour,

Merci d'avoir ouvert cette issue. Effectivement cette description semble être erronée.

Nous n'avons pas la possibilité de corriger les erreurs sur les schémas dont nous ne sommes pas auteurs.

La page web de [ce schéma](https://schema.data.gouv.fr/scdl/equipements/latest.html) indique que vous pouvez remonter cette erreur de deux façons :
- directement sur le dépôt Git du schéma : https://git.opendatafrance.net/scdl/equipements
- par e-mail : `scdl@opendatafrance.email`

Je vous invite en conséquence à entrer en contact avec OpenDataFrance pour faire remonter ce problème.

**Comment by ele-gall-ac-mineducation** [comment]
C’est fait, désolé pour la PR « É & ’ » entretemps, je vais leur pousser aussi.

**Comment by AntoineAugusti** [comment]
Effectivement, la PR https://github.com/etalab/schema.data.gouv.fr/pull/61 doit être adressée directement au producteur.

schema.data.gouv.fr se contente de valider que les schémas respectent les standards et d'agréger les schémas mais ne peut corriger de telles erreurs.
