### ISSUE TITLE
schéma des actes budgétaires

### ISSUE THREAD

**Issue by akakeronos** [etalab/schema.data.gouv.fr#63]
Dans le cadre de l'association Open Data France, un groupe de travail s'est constitué afin de proposer un schéma simplifié des données budgétaires. Ce travail se base sur les champs existants dans les fichiers dits TOTEM transmis à la Direction Générale des Collectivités Locales par les collectivités publiques qui ont procédé à la dématérialisation de cette transmission réglementaire.

Une page de documentation détaille l'état d'avancement de ce projet : https://opendatafrance.gitbook.io/scdl/documents-de-travail/schemas-preparation/budgets

**Comment by AntoineAugusti** [comment]
Le schéma a été ajouté dans la PR #69 et est maintenant disponible sur schema.data.gouv.fr : https://schema.data.gouv.fr/scdl/budget/latest.html

**Comment by akakeronos** [comment]
Merci !

**Comment by akakeronos** [comment]
En regardant la documentation générée je me suis aperçu de problèmes de mise en forme dans le schéma json que je viens de corriger

**Comment by AntoineAugusti** [comment]
@akakeronos Parfait ! Pour faire apparaitre vos modifications vous pouvez :

- faire vos corrections dans le fichier JSON du schéma / le README
- incrémenter la version dans le schéma et les différents liens
- tagguer une nouvelle version sur Git, la même sur le schéma (`0.2.1` je pense comme c'est une correction de la `0.2`)
- la nouvelle version sera automatiquement récupérée, validée puis publiée
