### ISSUE TITLE
schéma des informations de restauration collectivité

### ISSUE THREAD

**Issue by akakeronos** [etalab/schema.data.gouv.fr#64]
Dans le cadre de l'association open data France un groupe de travail va se consituter afin de proposer un standard de description des données relatives au contenu des menus proposés par les opérateurs de restauration collective.

Ces informations doivent permettre de décrire les menus, les plats qui les composent, les produits qui entrent dans la composition de ces plats et enfin les ingrédients qui sont présents dans ces produits.

Des liens avec la base de données ouverte Open Food Facts sont envisagés et plusieurs types de réutilisation de ces informations sont d'ors et déjà envisagés.

Un document contenant l'état d'avancement de la réflexion en cours est disponible ici https://opendatafrance.gitbook.io/scdl/documents-de-travail/schemas-preparation/menus

**Comment by AntoineAugusti** [comment]
Commentaire relayant une information provenant d'OpenDataFrance.

---

## Description du schéma

Cette initiative vide à standardiser la publication des jeux de données relatifs aux offres de restauration collective. Elle concerne la restauration scolaire mais peut s'étendre aux offres de restauration pour les personnes âgées, les restaurants administratifs ou les centres de loisirs. Elle s'articule autour des notions de menus, des plats qui les composent et des denrées utilisées pour les fabriquer.

En utilisant ce niveau de granularité, les organismes publics qui souhaitent uniquement publier leurs menus peuvent le faire et ceux qui peuvent fournir plus d'informations disposent des champs de description nécessaires.
En décrivant les denrées qui constituent les plats proposés dans les menus de restauration collective il sera possible de relier ces données à celle d'open food facts ou de calculer le bilan carbone des plats fabriqués.

Durant la période de confinement, nous avons finalisé le bien connu jeu de données "Menu des Cantines" et nous pensons être arrivés à un format assez complet, déjà validé par le groupe de collectivité associées à son élaboration.

Nous ouvrons maintenant la discussion avec l’ensemble des collectivités pour vous demander vos avis. L’appel à commentaire est **ouvert jusqu’au 15 juillet.**

## Liens
Le standard Menu des Cantines est décrit le référentiel suivant :
https://opendatafrance.gitbook.io/scdl/documents-de-travail/schema-en-discussion/menus
https://opendatafrance.gitbook.io/scdl/documents-de-travail/schema-en-discussion/plats-des-menus

Si vous avez des commentaires à faire, des questions à poser, je vous prie de le faire dans le document en ligne suivant :
https://semestriel.framapad.org/p/43ujk0n8ig-9hgz

Vous constatez qu’il est composé de deux jeux de données : celui des Menu (que beaucoup d’entre-vous connaissent) et celui de la composition des plats, qui est un approfondissement des produits utilisés et qui reste pour l’instant optionnel.

## Stade d'avancement

Mon schéma est :

- [ ] **en investigation :** il est envisagé de créer un schéma pour modéliser une situation
- [x] **en cours d'élaboration :** ce schéma fait l'objet de discussions auprès de multiples partenaires
- [ ] **en construction :** ce schéma est en cours d'implémentation après son élaboration

**Comment by geoffreyaldebert** [comment]
Duplicate #149
