### ISSUE TITLE
[irve] ISO 8601 pour date_maj ?

### ISSUE THREAD

**Issue by loichay** [etalab/schema.data.gouv.fr#7]
Pourquoi la date de mise à jour des données est-elle exprimée au format AAAA/MM/JJ et pas AAAA-MM-JJ plus conforme à la norme internationale ISO 8601 ? Ne faudrait-il pas remplacer le séparateur / par - ?

**Comment by abulte** [comment]
@loichay comme tu le sais certainement déjà, c'est l'arrêté qui nous impose ce format https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000033860733&categorieLien=id.

**Comment by AntoineAugusti** [comment]
Je ferme car on ne peut pas modifier facilement ceci pour le moment.
