### ISSUE TITLE
Versionnage des schémas

### ISSUE THREAD

**Issue by ColinMaudry** [etalab/schema.data.gouv.fr#76]
Les spécifications d'un schéma sont souvent amenées à changer. Par exemple, les spécifications du schéma des données essentielles de la commande publique ont été modifiées par des arrêtés successifs.

Problème : comment proposer une architecture qui permette à la fois

- une récupération facile des différentes versions d'un même schéma par les utilisateurs
- une mise à disposition facile par les administrateurs du schéma

Scénario cible idéal :

- URL de publication des schémas standardisées (facile pour les utilisateurs) :
  - https://schema.data.gouv.fr/code_du_schéma/ = documentation du schéma. Exemple : https://schema.data.gouv.fr/marches-publics/
  -   https://schema.data.gouv.fr/code_du_schéma/format/n = téléchargement de version `n` du schéma, en version `format`. Exemple : https://schema.data.gouv.fr/marches-publics/json/1.1.2
- Système de redirection d'URL vers les URL de publication réelles
  - sur le modèle de W3id (https://github.com/perma-id/w3id.org#permanent-identifiers-for-the-web) : redirections 301 configurables par les administrateurs du schéma

**Comment by AntoineAugusti** [comment]
Salut @ColinMaudry,

schema.data.gouv.fr dispose déjà d'un mécanisme d'URLs stables dans le temps pour la documentation et les schémas exposés, avec le support de versions  (et la possibilité de demander la dernière version).

Ceci est expliqué sur [la page suivante](https://schema.data.gouv.fr/documentation/integration-autres-systemes#urls-stables).

Est-ce que ceci te convient ?

**Comment by ColinMaudry** [comment]
@AntoineAugusti Ça l'air top ! Juste pour que je comprenne bien : dans le cas des DECP, je vise la cible suivante : un seul schéma (deux aujourd'hui) disponible dans n versions.

Comment est-ce que j'associe une version à une URL de schéma ? Comment je lie une version (x.y.z) à une version du schéma JSON ?

**Comment by AntoineAugusti** [comment]
Tu as les URLs suivants pour ton cas :

- https://schema.data.gouv.fr/schemas/etalab/format-commande-publique/1.3.0/contrats-concessions.json
- https://schema.data.gouv.fr/schemas/etalab/format-commande-publique/1.3.0/march%C3%A9s.json
- https://schema.data.gouv.fr/etalab/format-commande-publique/1.3.0.html

Pour le HTML, quand tu mets un lien vers la dernière version tu as une 301 vers `latest.html` si c'est la dernière version. Les anciens liens restent toujours valides après publication de nouvelles versions.

**Comment by AntoineAugusti** [comment]
Hello @ColinMaudry,

Peut-on fermer cette issue ?

**Comment by ColinMaudry** [comment]
Merci Antoine, c'est clair :grinning:
