### ISSUE TITLE
Référencement de champ code SIREN et caractère obligatoire

### ISSUE THREAD

**Issue by Fonaine** [etalab/schema.data.gouv.fr#82]
Bonjour,
sur le schéma DAE, plusieurs colonnes ont été référencées avec des vérificateurs french-siren-value
https://schema.data.gouv.fr/arsante/schema-dae/latest.html

Si le système de vérification fonctionne correctement, je ne parviens par à rendre le champ "non obligatoire" malgré un paramétrage required à false (champs mnt_siren, fab_siren). 

Ai-je raté quelque chose ? 
Merci d'avance.

**Comment by AntoineAugusti** [comment]
Hmm, il y a potentiellement un bug. Je pensais que le fait que le champ soit marqué en required ait une influence sur le check du SIREN.

L'implémentation du check est dans ce commit : https://git.opendatafrance.net/validata/validata-core/commit/b9d85421014cab52162dddf41f8a9a115f2b727c

@cbenz, sais-tu s'il faut ajouter une condition supplémentaire dans ce check précisément ?

**Comment by cbenz** [comment]
C'est un piège lié à table-schema assez classique : "required = false" indique que la *valeur* n'est pas obligatoire (une valeur "null" acceptée), mais dans tous les cas la colonne est obligatoire.

Cf https://frictionlessdata.io/specs/table-schema/ où je trouve que ce n'est pas très explicite.

**Comment by AntoineAugusti** [comment]
Là j'ai l'impression que c'est la combinaison required false + custom check qui pose problème. Si on met une valeur nulle, le required ne pose pas problème mais le custom check met une erreur.

**Comment by cbenz** [comment]
Existe-t-il un fichier qui mette permette de reproduire le bug ?

**Comment by AntoineAugusti** [comment]
Je viens de créer un tel fichier. Il comporte d'autres erreurs mais fait apparaître le problème en question ici

- [Fichier](https://gist.github.com/AntoineAugusti/f569487bdbb28fd6d0ad4cf0059e7381) 
- [Lien Validata](https://validata.etalab.studio/table-schema?input=url&schema_name=schema-datagouv-fr.arsante%2Fschema-dae&schema_ref=&url=https%3A%2F%2Fgist.githubusercontent.com%2FAntoineAugusti%2Ff569487bdbb28fd6d0ad4cf0059e7381%2Fraw%2Fe21f1c094b6d0af151227ebffcc557a52a09b100%2Fdae_bug_siren.csv)

**Comment by AntoineAugusti** [comment]
@cbenz Penses-tu que c'est un cas qui doit être géré dans le custom check ?

**Comment by cbenz** [comment]
Désolé du délai, je vais essayer de voir ça cet après-midi. Je dois creuser un peu :)

**Comment by cbenz** [comment]
@AntoineAugusti J'ai regardé rapidement [les checks de goodtables](https://github.com/frictionlessdata/goodtables-py/tree/master/goodtables/checks) et ça me donne l'impression que les custom checks SIREN, SIRET, etc. doivent en effet tester la présence de valeur avant de faire leur test.

Après coup, j'ai vu qu'un autre custom check faisait pareil : [nomenclature_actes_value.py](https://git.opendatafrance.net/validata/validata-core/blob/019680c566e46c678bc38103244bf12523d161d5/validata_core/custom_checks/nomenclature_actes_value.py#L80-83).

J'ai proposé une merge request : https://git.opendatafrance.net/validata/validata-core/merge_requests/8

Pourrais-tu tester et éventuellement participer à la merge request, avant que je ne la merge ?

Au fait il est intéressant de noter que les checks travaillent sur les lignes entières, pas seulement les cellules. À mon avis c'est pour cela que Goodtables envoie une valeur vide au check, même si la cellule est "required".

**Comment by AntoineAugusti** [comment]
Merci @cbenz ! J'ai laissé un commentaire là-bas et je regarderai la suite de la discussion.

**Comment by johanricher** [comment]
@AntoineAugusti Ca a été mergé de notre côté, est-ce que c'est bon pour vous ? Sinon il faudra attendre un peu qu'on release des nouvelles versions de `validata-core` et `validata-ui` prenant en compte ce fix.

**Comment by AntoineAugusti** [comment]
J'attends les releases de Validata pour que ce soit définitivement clôturé ici. J'ai besoin également d'un fix sur Goodtables, donc ce serait idéal que tout ceci soit disponible dans la prochaine version de Validata 🙏 https://github.com/frictionlessdata/goodtables-py/pull/333

**Comment by johanricher** [comment]
Ca y est des nouvelles versions de Validata ([core](https://git.opendatafrance.net/validata/validata-core/-/tags/v0.5.7), [api](https://git.opendatafrance.net/validata/validata-api/-/tags/v0.3.7), [ui](https://git.opendatafrance.net/validata/validata-ui/-/tags/v0.3.10)) sont sorties grâce au travail de @pierredittgen. :clap: Utilisation de [validata-docker](https://git.opendatafrance.net/validata/validata-docker) recommandée, bien sûr

**Comment by AntoineAugusti** [comment]
@johanricher @pierredittgen Merci beaucoup à vous deux ! On va faire la mise à jour de Validata côté Etalab dans les jours à venir.
