### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ele-gall-ac-mineducation** [etalab/schema.data.gouv.fr#90]
dans le [README.md](https://github.com/etalab/schema.data.gouv.fr/blob/master/README.md#à-venir)

défibrilateur → défibrillateur

**Comment by AntoineAugusti** [comment]
Merci ! Je vais en profiter pour réécrire le README, qui est obsolète #90

**Comment by ele-gall-ac-mineducation** [comment]
De rien. J’ai pris l’habitude de passer Grammalecte sur « nos* » pages quand j’y cherche des informations.

* en tant qu’agent public.
