### ISSUE TITLE
Dans la documentation, ajouter un lien vers ce dépôt 

### ISSUE THREAD

**Issue by bzg** [etalab/schema.data.gouv.fr#98]
Ce [lien](https://schema.data.gouv.fr/documentation/ajouter-un-schema#r%C3%A9f%C3%A9rencer-son-sch%C3%A9ma) indique ce qu'il faut modifier dans [schema.data.gouv.fr](https://github.com/etalab/schema.data.gouv.fr/issues/new) pour ajouter un schéma, mais il n'est pas fait mention du dépôt lui-même.  Ce serait utile que ce soit le cas.

Le lien `repertoires.yml` est cliquable, mais ça reste peu explicite.

**Comment by AntoineAugusti** [comment]
Merci @bzg, j'ai proposé une PR pour rendre ça plus explicite

**Comment by bzg** [comment]
Merci !
